name: Build and Push Helm Chart
description: Lint, build, and optionally push Helm chart to Google Artifact Registry
inputs:
  chart-path:
    description: Path to the Helm chart directory
    required: true
  push:
    description: Whether to push the chart to registry
    required: false
    default: 'false'
  registry-login-url:
    description: GRegistry login URL (e.g., oci://europe-docker.pkg.dev/project/helm-charts)
    required: false
    default: "https://europe-docker.pkg.dev"
  registry-url:
    description: Google Artifact Registry URL (e.g., oci://europe-docker.pkg.dev/project/helm-charts)
    required: false
  credentials:
    description: Base64 encoded Google service account JSON credentials
    required: false
  version:
    description: Chart version (defaults to 0.0.0-{sha})
    required: false
  app-version:
    description: App version (defaults to git sha)
    required: false

outputs:
  chart-name:
    description: Name of the packaged chart file
    value: ${{ steps.package.outputs.chart-name }}
  chart-version:
    description: Version of the packaged chart
    value: ${{ steps.set-version.outputs.version }}

runs:
  using: composite
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: latest

    - name: Set version
      id: set-version
      shell: bash
      run: |
        if [ -n "${{ inputs.version }}" ]; then
          VERSION="${{ inputs.version }}"
        else
          VERSION="0.0.0-${GITHUB_SHA::8}"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Update Helm dependencies
      shell: bash
      run: helm dependency update ${{ inputs.chart-path }}

    - name: Lint Helm chart
      shell: bash
      run: helm lint ${{ inputs.chart-path }}

    - name: Package Helm chart
      id: package
      shell: bash
      run: |
        helm package ${{ inputs.chart-path }} \
          --version ${{ steps.set-version.outputs.version }}
        
        CHART_NAME=$(ls -1 *.tgz | head -n1)
        echo "chart-name=$CHART_NAME" >> $GITHUB_OUTPUT

    - name: Authenticate to Google Artifact Registry
      if: inputs.push == 'true'
      shell: bash
      run: |
        echo "${{ inputs.credentials }}" | \
          helm registry login -u _json_key_base64 \
          --password-stdin ${{ inputs.registry-login-url }}

    - name: Push Helm chart
      if: inputs.push == 'true'
      shell: bash
      run: |
        helm push ${{ steps.package.outputs.chart-name }} ${{ inputs.registry-url }}

    - name: Cleanup credentials
      if: always() && inputs.push == 'true'
      shell: bash
      run: |
        rm -f /tmp/gcloud-key.json
