apiVersion: batch/v1
kind: CronJob
metadata:
  name: enable-factory-crisis
spec:
  schedule: "00 16 * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      template:
        spec:
          containers:
            - name: enable-factory-crisis
              image: curlimages/curl
              imagePullPolicy: IfNotPresent
              args:
                - "http://feature-flag-service:8080/v1/flags/factory_crisis"
                - "-X"
                - "PUT"
                - "-H"
                - "Content-Type: application/json"
                - "-d"
                - '{"enabled": true}'
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: disable-factory-crisis
spec:
  schedule: "00 19 * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      template:
        spec:
          containers:
            - name: disable-factory-crisis
              image: curlimages/curl
              imagePullPolicy: IfNotPresent
              args:
                - "http://feature-flag-service:8080/v1/flags/factory_crisis"
                - "-X"
                - "PUT"
                - "-H"
                - "Content-Type: application/json"
                - "-d"
                - '{"enabled": false}'
          restartPolicy: OnFailure
