services:
  background-service:
    image: ${REGISTRY}/background-service:${TAG}
    build:
      context: src/background-service

  broker-service:
    image: ${REGISTRY}/broker-service:${TAG}
    build:
      context: src/broker-service

  contentcreator:
    image: ${REGISTRY}/contentcreator:${TAG}
    build:
      context: src/contentcreator

  credit-card-order-service:
    image: ${REGISTRY}/credit-card-order-service:${TAG}
    build:
      context: src/credit-card-order-service

  db:
    image: ${REGISTRY}/db-${DB_TYPE}:${TAG}
    build:
      context: src/db/${DB_TYPE}

  db-adapter:
    image: ${REGISTRY}/db-adapter:${TAG}
    build:
      context: src/db-adapter

  feature-flag-service:
    image: ${REGISTRY}/feature-flag-service:${TAG}
    build:
      context: src/feature-flag-service

  frontend:
    image: ${REGISTRY}/frontend:${TAG}
    build:
      context: src/frontend

  frontendreverseproxy:
    image: ${REGISTRY}/frontendreverseproxy:${TAG}
    build:
      context: src/frontendreverseproxy

  loadgen:
    image: ${REGISTRY}/loadgen:${TAG}
    build:
      context: src/loadgen

  offerservice:
    image: ${REGISTRY}/offerservice:${TAG}
    build:
      context: src/offerservice

  pricing-service:
    image: ${REGISTRY}/pricing-service:${TAG}
    build:
      context: src/pricing-service

  problem-operator:
    image: ${REGISTRY}/problem-operator:${TAG}
    build:
      context: src/problem-operator

  third-party-service:
    image: ${REGISTRY}/third-party-service:${TAG}
    build:
      context: src/third-party-service

  user-service:
    image: ${REGISTRY}/user-service:${TAG}
    build:
      context: src/user-service
