x-service: &default-service
  restart: always


x-connection-strings:
  JAVA_CONNECTION_STRING: &java-connection-string jdbc:sqlserver://db:1433;database=TradeManagement;user=sa;password=yourStrong(!)Password;encrypt=false;trustServerCertificate=false;loginTimeout=30;
  DOTNET_CONNECTION_STRING: &dotnet-connection-string Data Source=db;Initial Catalog=TradeManagement;Persist Security Info=True;User ID=sa;Password=yourStrong(!)Password;TrustServerCertificate=true
  GO_CONNECTION_STRING: &go-connection-string sqlserver://sa:yourStrong(!)Password@db:1433?database=TradeManagement&connection+encrypt=false&connection+TrustServerCertificate=false&connection+loginTimeout=30

services:
  db:
    <<: *default-service
    build: src/db/${DB_TYPE}
    ports:
      - 1433:1433
      - 5432:5432
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  pricing-service:
    <<: *default-service
    build:
      context: src/
      dockerfile: pricing-service/Dockerfile
    depends_on:
      - db-adapter
    ports:
      - 8083:8080
    environment:
      DB_ADAPTER_ADDRESS: db-adapter:50051
      PROXY_PREFIX: pricing-service

  broker-service:
    <<: *default-service
    build:
      context: src/
      dockerfile: broker-service/Dockerfile
    ports:
      - 8084:8080
    depends_on:
      - db-adapter
      - user-service
      - pricing-service
      - feature-flag-service
    environment:
      USER_SERVICE_ADDRESS: http://user-service:8080
      PRICING_SERVICE_ADDRESS: http://pricing-service:8080
      FEATURE_FLAG_SERVICE_ADDRESS: http://feature-flag-service:8080
      PROXY_PREFIX: broker-service
      DB_ADAPTER_ADDRESS: db-adapter:50051

  frontend:
    <<: *default-service
    build:
      context: src/frontend
      dockerfile: Dockerfile.dev
      # dockerfile: Dockerfile
    # depends_on:
    #   - broker-service
    #   - user-service
    #   - pricing-service
    #   - credit-card-order-service
    ports:
      - 8092:3000
    volumes:
      - ./src/frontend/src:/app/src:ro

  frontendreverseproxy:
    <<: *default-service
    build: src/frontendreverseproxy
    depends_on:
      - broker-service
      - frontend
      - pricing-service
      - feature-flag-service
      - offerservice
      - credit-card-order-service
      - background-service
    ports:
      - 80:80

  loadgen:
    <<: *default-service
    build: src/loadgen
    depends_on:
      - frontendreverseproxy
    environment:
      EASYTRADE_URL: http://frontendreverseproxy

  offerservice:
    <<: *default-service
    build:
      context: src/
      dockerfile: offerservice/Dockerfile
    depends_on:
      - db-adapter
      - user-service
      - feature-flag-service
    ports:
      - 8087:8080
    environment:
      DB_ADAPTER_ADDRESS: db-adapter:50051
      USER_SERVICE_ADDRESS: http://user-service:8080
      FEATURE_FLAG_SERVICE_ADDRESS: http://feature-flag-service:8080

  user-service:
    <<: *default-service
    build:
      context: src/
      dockerfile: user-service/Dockerfile
    depends_on:
      - db-adapter
    ports:
      - 8089:8080
    environment:
      DB_ADAPTER_ADDRESS: db-adapter:50051
      
  credit-card-order-service:
    <<: *default-service
    build:
      context: src/
      dockerfile: credit-card-order-service/Dockerfile
    depends_on:
      - db-adapter
      - background-service
    ports:
      - 8091:8080
    environment:
      PROXY_PREFIX: credit-card-order-service
      DB_ADAPTER_ADDRESS: db-adapter:50051
      THIRD_PARTY_SERVICE_ADDRESS: http://background-service:8080
      FEATURE_FLAG_SERVICE_ADDRESS: http://feature-flag-service:8080
      WORK_DELAY: 30
      WORK_RATE: 30
      JAVA_TOOL_OPTIONS: "-XX:-OmitStackTraceInFastThrow"

  feature-flag-service:
    <<: *default-service
    build: src/feature-flag-service
    ports:
      - 8094:8080
    environment:
      PROXY_PREFIX: feature-flag-service
      # ENABLE_MODIFY: "false"
      # ENABLE_FRONTEND_MODIFY: "false"

  db-adapter:
    <<: *default-service
    build:
      context: src/
      dockerfile: db-adapter/Dockerfile
    depends_on:
      - db
    ports:
      - 50051:50051
    environment:
      DB_TYPE: ${DB_TYPE}
      DB_URL: ${DB_URL}

  background-service:
    <<: *default-service
    build:
      context: src/
      dockerfile: background-service/Dockerfile
    depends_on:
      - offerservice
      - db-adapter
    ports:
      - 8095:8080
    environment:
      OFFER_SERVICE_ADDRESS: http://offerservice:8080
      FEATURE_FLAG_SERVICE_ADDRESS: http://feature-flag-service:8080
      CREDIT_CARD_ORDER_SERVICE_ADDRESS: http://credit-card-order-service:8080
      DB_ADAPTER_SERVICE_ADDRESS: db-adapter:50051
      THIRD_PARTY_DELAY: 10
      THIRD_PARTY_RATE: 10
      DELAY_CHANCE_PERCENT: 20


