services:
  aggregator-service:
    image: ${REGISTRY}/aggregator-service:${TAG}
    build:
      context: src/aggregator-service

  broker-service:
    image: ${REGISTRY}/broker-service:${TAG}
    build:
      context: src/
      dockerfile: broker-service/Dockerfile

  calculationservice:
    image: ${REGISTRY}/calculationservice:${TAG}
    build:
      context: src/calculationservice

  contentcreator:
    image: ${REGISTRY}/contentcreator:${TAG}
    build:
      context: src/contentcreator

  credit-card-order-service:
    image: ${REGISTRY}/credit-card-order-service:${TAG}
    build:
      context: src/
      dockerfile: credit-card-order-service/Dockerfile

  db:
    image: ${REGISTRY}/db-${DB_TYPE}:${TAG}
    build:
      context: src/db/${DB_TYPE}

  db-adapter:
    image: ${REGISTRY}/db-adapter:${TAG}
    build:
      context: src/
      dockerfile: db-adapter/Dockerfile

  feature-flag-service:
    image: ${REGISTRY}/feature-flag-service:${TAG}
    build:
      context: src/feature-flag-service

  frontend:
    image: ${REGISTRY}/frontend:${TAG}
    build:
      context: src/frontend

  frontendreverseproxy:
    image: ${REGISTRY}/frontendreverseproxy:${TAG}
    build:
      context: src/frontendreverseproxy

  loadgen:
    image: ${REGISTRY}/loadgen:${TAG}
    build:
      context: src/loadgen

  manager:
    image: ${REGISTRY}/manager:${TAG}
    build:
      context: src/manager/easyTradeManager

  offerservice:
    image: ${REGISTRY}/offerservice:${TAG}
    build:
      context: src/
      dockerfile: offerservice/Dockerfile

  pricing-service:
    image: ${REGISTRY}/pricing-service:${TAG}
    build:
      context: src/
      dockerfile: pricing-service/Dockerfile

  problem-operator:
    image: ${REGISTRY}/problem-operator:${TAG}
    build:
      context: src/problem-operator

  rabbitmq:
    image: ${REGISTRY}/rabbitmq:${TAG}
    build:
      context: src/rabbitmq

  third-party-service:
    image: ${REGISTRY}/third-party-service:${TAG}
    build:
      context: src/third-party-service

  user-service:
    image: ${REGISTRY}/user-service:${TAG}
    build:
      context: src/user-service
