x-logging: &default-logging
  driver: json-file
  options:
    max-file: "5"
    max-size: "10m"

x-service: &default-service
  restart: always
  logging: *default-logging


x-connection-strings:
  JAVA_CONNECTION_STRING: &java-connection-string jdbc:sqlserver://db:1433;database=TradeManagement;user=sa;password=yourStrong(!)Password;encrypt=false;trustServerCertificate=false;loginTimeout=30;
  DOTNET_CONNECTION_STRING: &dotnet-connection-string Data Source=db;Initial Catalog=TradeManagement;Persist Security Info=True;User ID=sa;Password=yourStrong(!)Password;TrustServerCertificate=true
  GO_CONNECTION_STRING: &go-connection-string sqlserver://sa:yourStrong(!)Password@db:1433?database=TradeManagement&connection+encrypt=false&connection+TrustServerCertificate=false&connection+loginTimeout=30

services:
  db:
    <<: *default-service
    image: ${REGISTRY}/db-${DB_TYPE}:${TAG}
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  pricing-service:
    <<: *default-service
    image: ${REGISTRY}/pricing-service:${TAG}
    depends_on:
      - db-adapter
    environment:
      DB_ADAPTER_ADDRESS: db-adapter:50051
      PROXY_PREFIX: pricing-service

  broker-service:
    <<: *default-service
    image: ${REGISTRY}/broker-service:${TAG}
    depends_on:
      - db-adapter
      - user-service
      - pricing-service
      - feature-flag-service
    environment:
      USER_SERVICE_ADDRESS: http://user-service:8080
      PRICING_SERVICE_ADDRESS: http://pricing-service:8080
      FEATURE_FLAG_SERVICE_ADDRESS: http://feature-flag-service:8080
      PROXY_PREFIX: broker-service
      DB_ADAPTER_ADDRESS: db-adapter:50051

  frontend:
    <<: *default-service
    image: ${REGISTRY}/frontend:${TAG}
    depends_on:
      - broker-service
      - user-service
      - pricing-service
      - credit-card-order-service

  frontendreverseproxy:
    <<: *default-service
    image: ${REGISTRY}/frontendreverseproxy:${TAG}
    depends_on:
      - broker-service
      - frontend
      - user-service
      - pricing-service
      - feature-flag-service
      - offerservice
      - credit-card-order-service
      - background-service
    ports:
      - 80:80

  loadgen:
    <<: *default-service
    image: ${REGISTRY}/loadgen:${TAG}
    depends_on:
      - frontendreverseproxy
    environment:
      EASYTRADE_URL: http://frontendreverseproxy

  offerservice:
    <<: *default-service
    image: ${REGISTRY}/offerservice:${TAG}
    depends_on:
      - user-service
      - db-adapter
    environment:
      DB_ADAPTER_ADDRESS: db-adapter:50051
      USER_SERVICE_ADDRESS: http://user-service:8080
      FEATURE_FLAG_SERVICE_ADDRESS: http://feature-flag-service:8080

  feature-flag-service:
    <<: *default-service
    image: ${REGISTRY}/feature-flag-service:${TAG}
    environment:
      PROXY_PREFIX: feature-flag-service

  user-service:
    <<: *default-service
    image: ${REGISTRY}/user-service:${TAG}
    depends_on:
      - db-adapter
    environment:
      DB_ADAPTER_ADDRESS: db-adapter:50051
      PROXY_PREFIX: user-service

  credit-card-order-service:
    <<: *default-service
    image: ${REGISTRY}/credit-card-order-service:${TAG}
    depends_on:
      - db-adapter
      - background-service
    environment:
      PROXY_PREFIX: credit-card-order-service
      DB_ADAPTER_ADDRESS: db-adapter:50051
      THIRD_PARTY_SERVICE_ADDRESS: http://background-service:8080
      FEATURE_FLAG_SERVICE_ADDRESS: http://feature-flag-service:8080
      WORK_DELAY: 300
      WORK_RATE: 900
      JAVA_TOOL_OPTIONS: "-XX:-OmitStackTraceInFastThrow"

  background-service:
    <<: *default-service
    image: ${REGISTRY}/background-service:${TAG}
    depends_on:
      - offerservice
    environment:
      OFFER_SERVICE_ADDRESS: http://offerservice:8080
      FEATURE_FLAG_SERVICE_ADDRESS: http://feature-flag-service:8080
      CREDIT_CARD_ORDER_SERVICE_ADDRESS: http://credit-card-order-service:8080
      DB_ADAPTER_SERVICE_ADDRESS: db-adapter:50051
      THIRD_PARTY_DELAY: 10
      THIRD_PARTY_RATE: 10
      DELAY_CHANCE_PERCENT: 20

