services:
  background-service:
    image: ${REGISTRY}/background-service:${TAG}
    build:
      context: src/background-service

  broker-service:
    image: ${REGISTRY}/broker-service:${TAG}
    build:
      context: src/
      dockerfile: broker-service/Dockerfile

  credit-card-order-service:
    image: ${REGISTRY}/credit-card-order-service:${TAG}
    build:
      context: src/
      dockerfile: credit-card-order-service/Dockerfile

  db:
    image: ${REGISTRY}/db-${DB_TYPE}:${TAG}
    build:
      context: src/db/${DB_TYPE}

  db-adapter:
    image: ${REGISTRY}/db-adapter:${TAG}
    build:
      context: src/
      dockerfile: db-adapter/Dockerfile

  feature-flag-service:
    image: ${REGISTRY}/feature-flag-service:${TAG}
    build:
      context: src/feature-flag-service

  frontend:
    image: ${REGISTRY}/frontend:${TAG}
    build:
      context: src/frontend

  frontend-reverse-proxy:
    image: ${REGISTRY}/frontend-reverse-proxy:${TAG}
    build:
      context: src/frontend-reverse-proxy

  load-gen:
    image: ${REGISTRY}/load-gen:${TAG}
    build:
      context: src/load-gen

  offer-service:
    image: ${REGISTRY}/offer-service:${TAG}
    build:
      context: src/
      dockerfile: offer-service/Dockerfile

  pricing-service:
    image: ${REGISTRY}/pricing-service:${TAG}
    build:
      context: src/
      dockerfile: pricing-service/Dockerfile

  user-service:
    image: ${REGISTRY}/user-service:${TAG}
    build:
      context: src/user-service
