apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculationservice
spec:
  selector:
    matchLabels:
      app: calculationservice
  template:
    metadata:
      labels:
        app: calculationservice
    spec:
      containers:
        - name: calculationservice
          image: calculationservice
          env: []
          envFrom:
            - configMapRef:
                name: rabbitmq-vars
          resources:
            requests:
              cpu: 10m
              memory: 25Mi
            limits:
              memory: 25Mi
