apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: db
          ports:
            - containerPort: 1433
          env:
            - name: SA_PASSWORD
              value: "yourStrong(!)Password"
          resources:
            requests:
              cpu: 40m
              memory: 1.5Gi
            limits:
              memory: 1.5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - name: mssql
      port: 1433
      targetPort: 1433
