apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine
spec:
  selector:
    matchLabels:
      app: engine
  template:
    metadata:
      labels:
        app: engine
    spec:
      containers:
        - name: engine
          image: engine
          ports:
            - containerPort: 8080
          env:
            - name: BROKER_HOSTANDPORT
              value: "broker-service:8080"
            - name: PROXY_PREFIX
              value: "engine"
          resources:
            requests:
              cpu: 10m
              memory: 450Mi
            limits:
              memory: 450Mi
---
apiVersion: v1
kind: Service
metadata:
  name: engine
spec:
  type: ClusterIP
  selector:
    app: engine
  ports:
    - name: http
      port: 8080
      targetPort: 8080
