apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - accountservice.yaml
  - aggregator-service.yaml
  - broker-service.yaml
  - calculationservice.yaml
  - connection-strings.yaml
  - contentcreator.yaml
  - credit-card-order-service.yaml
  - db.yaml
  - engine.yaml
  - feature-flag-service-setup.yaml
  - feature-flag-service.yaml
  - frontend.yaml
  - frontendreverseproxy.yaml
  - loginservice.yaml
  - manager.yaml
  - offerservice.yaml
  - pricing-service.yaml
  - rabbitmq.yaml
  - third-party-service.yaml
  - loadgen.yaml
  - problem-operator.yaml
patches:
  - path: labels-and-envs.yaml
    target:
      kind: Deployment
