apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loadgen
  name: loadgen
spec:
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      labels:
        app: loadgen
    spec:
      containers:
        - name: loadgen
          image: loadgen
          env:
            - name: EASYTRADE_URL
              value: "http://frontendreverseproxy-easytrade"
            - name: RARE_VISITS_INTERVAL_MINUTES
              value: "60"
          resources:
            requests:
              cpu: "1"
              memory: 2Gi
            limits:
              memory: 2Gi
