apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginservice
spec:
  selector:
    matchLabels:
      app: loginservice
  template:
    metadata:
      labels:
        app: loginservice
    spec:
      containers:
        - name: loginservice
          image: loginservice
          ports:
            - containerPort: 8080
          env:
            - name: PROXY_PREFIX
              value: "loginservice"
            - name: MSSQL_CONNECTIONSTRING
              valueFrom:
                configMapKeyRef:
                  name: connection-strings
                  key: DOTNET_CONNECTION_STRING
          resources:
            requests:
              cpu: 20m
              memory: 450Mi
            limits:
              memory: 450Mi
---
apiVersion: v1
kind: Service
metadata:
  name: loginservice
spec:
  type: ClusterIP
  selector:
    app: loginservice
  ports:
    - name: http
      port: 8080
      targetPort: 8080
