apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-service
spec:
  selector:
    matchLabels:
      app: pricing-service
  template:
    metadata:
      labels:
        app: pricing-service
    spec:
      containers:
        - name: pricing-service
          image: pricing-service
          ports:
            - containerPort: 8080
          env:
            - name: PROXY_PREFIX
              value: "pricing-service"
            - name: MSSQL_CONNECTIONSTRING
              valueFrom:
                configMapKeyRef:
                  name: connection-strings
                  key: GO_CONNECTION_STRING
          envFrom:
            - configMapRef:
                name: rabbitmq-vars
          resources:
            requests:
              cpu: 20m
              memory: 80Mi
            limits:
              memory: 80Mi
---
apiVersion: v1
kind: Service
metadata:
  name: pricing-service
spec:
  type: ClusterIP
  selector:
    app: pricing-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
