// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: balance_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BalanceService_CreateBalance_FullMethodName                 = "/easytrade.dbadapter.balance.BalanceService/CreateBalance"
	BalanceService_GetBalanceByAccountId_FullMethodName         = "/easytrade.dbadapter.balance.BalanceService/GetBalanceByAccountId"
	BalanceService_UpdateBalance_FullMethodName                 = "/easytrade.dbadapter.balance.BalanceService/UpdateBalance"
	BalanceService_AddBalanceHistory_FullMethodName             = "/easytrade.dbadapter.balance.BalanceService/AddBalanceHistory"
	BalanceService_DeleteBalanceHistoryOlderThan_FullMethodName = "/easytrade.dbadapter.balance.BalanceService/DeleteBalanceHistoryOlderThan"
)

// BalanceServiceClient is the client API for BalanceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BalanceServiceClient interface {
	CreateBalance(ctx context.Context, in *CreateBalanceRequest, opts ...grpc.CallOption) (*BalanceMessage, error)
	GetBalanceByAccountId(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*BalanceMessage, error)
	UpdateBalance(ctx context.Context, in *UpdateBalanceRequest, opts ...grpc.CallOption) (*BalanceMessage, error)
	AddBalanceHistory(ctx context.Context, in *AddBalanceHistoryRequest, opts ...grpc.CallOption) (*BalanceHistoryMessage, error)
	DeleteBalanceHistoryOlderThan(ctx context.Context, in *DeleteBeforeRequest, opts ...grpc.CallOption) (*BatchResponse, error)
}

type balanceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBalanceServiceClient(cc grpc.ClientConnInterface) BalanceServiceClient {
	return &balanceServiceClient{cc}
}

func (c *balanceServiceClient) CreateBalance(ctx context.Context, in *CreateBalanceRequest, opts ...grpc.CallOption) (*BalanceMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalanceMessage)
	err := c.cc.Invoke(ctx, BalanceService_CreateBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceServiceClient) GetBalanceByAccountId(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*BalanceMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalanceMessage)
	err := c.cc.Invoke(ctx, BalanceService_GetBalanceByAccountId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceServiceClient) UpdateBalance(ctx context.Context, in *UpdateBalanceRequest, opts ...grpc.CallOption) (*BalanceMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalanceMessage)
	err := c.cc.Invoke(ctx, BalanceService_UpdateBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceServiceClient) AddBalanceHistory(ctx context.Context, in *AddBalanceHistoryRequest, opts ...grpc.CallOption) (*BalanceHistoryMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalanceHistoryMessage)
	err := c.cc.Invoke(ctx, BalanceService_AddBalanceHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceServiceClient) DeleteBalanceHistoryOlderThan(ctx context.Context, in *DeleteBeforeRequest, opts ...grpc.CallOption) (*BatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchResponse)
	err := c.cc.Invoke(ctx, BalanceService_DeleteBalanceHistoryOlderThan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BalanceServiceServer is the server API for BalanceService service.
// All implementations must embed UnimplementedBalanceServiceServer
// for forward compatibility.
type BalanceServiceServer interface {
	CreateBalance(context.Context, *CreateBalanceRequest) (*BalanceMessage, error)
	GetBalanceByAccountId(context.Context, *GetBalanceRequest) (*BalanceMessage, error)
	UpdateBalance(context.Context, *UpdateBalanceRequest) (*BalanceMessage, error)
	AddBalanceHistory(context.Context, *AddBalanceHistoryRequest) (*BalanceHistoryMessage, error)
	DeleteBalanceHistoryOlderThan(context.Context, *DeleteBeforeRequest) (*BatchResponse, error)
	mustEmbedUnimplementedBalanceServiceServer()
}

// UnimplementedBalanceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBalanceServiceServer struct{}

func (UnimplementedBalanceServiceServer) CreateBalance(context.Context, *CreateBalanceRequest) (*BalanceMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBalance not implemented")
}
func (UnimplementedBalanceServiceServer) GetBalanceByAccountId(context.Context, *GetBalanceRequest) (*BalanceMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalanceByAccountId not implemented")
}
func (UnimplementedBalanceServiceServer) UpdateBalance(context.Context, *UpdateBalanceRequest) (*BalanceMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBalance not implemented")
}
func (UnimplementedBalanceServiceServer) AddBalanceHistory(context.Context, *AddBalanceHistoryRequest) (*BalanceHistoryMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method AddBalanceHistory not implemented")
}
func (UnimplementedBalanceServiceServer) DeleteBalanceHistoryOlderThan(context.Context, *DeleteBeforeRequest) (*BatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBalanceHistoryOlderThan not implemented")
}
func (UnimplementedBalanceServiceServer) mustEmbedUnimplementedBalanceServiceServer() {}
func (UnimplementedBalanceServiceServer) testEmbeddedByValue()                        {}

// UnsafeBalanceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BalanceServiceServer will
// result in compilation errors.
type UnsafeBalanceServiceServer interface {
	mustEmbedUnimplementedBalanceServiceServer()
}

func RegisterBalanceServiceServer(s grpc.ServiceRegistrar, srv BalanceServiceServer) {
	// If the following call panics, it indicates UnimplementedBalanceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BalanceService_ServiceDesc, srv)
}

func _BalanceService_CreateBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServiceServer).CreateBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceService_CreateBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServiceServer).CreateBalance(ctx, req.(*CreateBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceService_GetBalanceByAccountId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServiceServer).GetBalanceByAccountId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceService_GetBalanceByAccountId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServiceServer).GetBalanceByAccountId(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceService_UpdateBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServiceServer).UpdateBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceService_UpdateBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServiceServer).UpdateBalance(ctx, req.(*UpdateBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceService_AddBalanceHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBalanceHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServiceServer).AddBalanceHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceService_AddBalanceHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServiceServer).AddBalanceHistory(ctx, req.(*AddBalanceHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceService_DeleteBalanceHistoryOlderThan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBeforeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServiceServer).DeleteBalanceHistoryOlderThan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceService_DeleteBalanceHistoryOlderThan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServiceServer).DeleteBalanceHistoryOlderThan(ctx, req.(*DeleteBeforeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BalanceService_ServiceDesc is the grpc.ServiceDesc for BalanceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BalanceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "easytrade.dbadapter.balance.BalanceService",
	HandlerType: (*BalanceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBalance",
			Handler:    _BalanceService_CreateBalance_Handler,
		},
		{
			MethodName: "GetBalanceByAccountId",
			Handler:    _BalanceService_GetBalanceByAccountId_Handler,
		},
		{
			MethodName: "UpdateBalance",
			Handler:    _BalanceService_UpdateBalance_Handler,
		},
		{
			MethodName: "AddBalanceHistory",
			Handler:    _BalanceService_AddBalanceHistory_Handler,
		},
		{
			MethodName: "DeleteBalanceHistoryOlderThan",
			Handler:    _BalanceService_DeleteBalanceHistoryOlderThan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "balance_service.proto",
}
