// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: balance_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BalanceMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceMessage) Reset() {
	*x = BalanceMessage{}
	mi := &file_balance_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceMessage) ProtoMessage() {}

func (x *BalanceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_balance_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceMessage.ProtoReflect.Descriptor instead.
func (*BalanceMessage) Descriptor() ([]byte, []int) {
	return file_balance_service_proto_rawDescGZIP(), []int{0}
}

func (x *BalanceMessage) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *BalanceMessage) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type BalanceHistoryMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	OldValue      float64                `protobuf:"fixed64,3,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	ValueChange   float64                `protobuf:"fixed64,4,opt,name=value_change,json=valueChange,proto3" json:"value_change,omitempty"`
	ActionType    string                 `protobuf:"bytes,5,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	ActionDate    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=action_date,json=actionDate,proto3" json:"action_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceHistoryMessage) Reset() {
	*x = BalanceHistoryMessage{}
	mi := &file_balance_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceHistoryMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceHistoryMessage) ProtoMessage() {}

func (x *BalanceHistoryMessage) ProtoReflect() protoreflect.Message {
	mi := &file_balance_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceHistoryMessage.ProtoReflect.Descriptor instead.
func (*BalanceHistoryMessage) Descriptor() ([]byte, []int) {
	return file_balance_service_proto_rawDescGZIP(), []int{1}
}

func (x *BalanceHistoryMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BalanceHistoryMessage) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *BalanceHistoryMessage) GetOldValue() float64 {
	if x != nil {
		return x.OldValue
	}
	return 0
}

func (x *BalanceHistoryMessage) GetValueChange() float64 {
	if x != nil {
		return x.ValueChange
	}
	return 0
}

func (x *BalanceHistoryMessage) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *BalanceHistoryMessage) GetActionDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ActionDate
	}
	return nil
}

type CreateBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBalanceRequest) Reset() {
	*x = CreateBalanceRequest{}
	mi := &file_balance_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBalanceRequest) ProtoMessage() {}

func (x *CreateBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBalanceRequest.ProtoReflect.Descriptor instead.
func (*CreateBalanceRequest) Descriptor() ([]byte, []int) {
	return file_balance_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBalanceRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateBalanceRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_balance_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_balance_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetBalanceRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type UpdateBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBalanceRequest) Reset() {
	*x = UpdateBalanceRequest{}
	mi := &file_balance_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBalanceRequest) ProtoMessage() {}

func (x *UpdateBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBalanceRequest.ProtoReflect.Descriptor instead.
func (*UpdateBalanceRequest) Descriptor() ([]byte, []int) {
	return file_balance_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateBalanceRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UpdateBalanceRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type AddBalanceHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	OldValue      float64                `protobuf:"fixed64,2,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	ValueChange   float64                `protobuf:"fixed64,3,opt,name=value_change,json=valueChange,proto3" json:"value_change,omitempty"`
	ActionType    string                 `protobuf:"bytes,4,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	ActionDate    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=action_date,json=actionDate,proto3" json:"action_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBalanceHistoryRequest) Reset() {
	*x = AddBalanceHistoryRequest{}
	mi := &file_balance_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBalanceHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBalanceHistoryRequest) ProtoMessage() {}

func (x *AddBalanceHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBalanceHistoryRequest.ProtoReflect.Descriptor instead.
func (*AddBalanceHistoryRequest) Descriptor() ([]byte, []int) {
	return file_balance_service_proto_rawDescGZIP(), []int{5}
}

func (x *AddBalanceHistoryRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AddBalanceHistoryRequest) GetOldValue() float64 {
	if x != nil {
		return x.OldValue
	}
	return 0
}

func (x *AddBalanceHistoryRequest) GetValueChange() float64 {
	if x != nil {
		return x.ValueChange
	}
	return 0
}

func (x *AddBalanceHistoryRequest) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *AddBalanceHistoryRequest) GetActionDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ActionDate
	}
	return nil
}

var File_balance_service_proto protoreflect.FileDescriptor

const file_balance_service_proto_rawDesc = "" +
	"\n" +
	"\x15balance_service.proto\x12\x1beasytrade.dbadapter.balance\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\"E\n" +
	"\x0eBalanceMessage\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"\xe4\x01\n" +
	"\x15BalanceHistoryMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x1b\n" +
	"\told_value\x18\x03 \x01(\x01R\boldValue\x12!\n" +
	"\fvalue_change\x18\x04 \x01(\x01R\vvalueChange\x12\x1f\n" +
	"\vaction_type\x18\x05 \x01(\tR\n" +
	"actionType\x12;\n" +
	"\vaction_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"actionDate\"K\n" +
	"\x14CreateBalanceRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"2\n" +
	"\x11GetBalanceRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"K\n" +
	"\x14UpdateBalanceRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"\xd7\x01\n" +
	"\x18AddBalanceHistoryRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1b\n" +
	"\told_value\x18\x02 \x01(\x01R\boldValue\x12!\n" +
	"\fvalue_change\x18\x03 \x01(\x01R\vvalueChange\x12\x1f\n" +
	"\vaction_type\x18\x04 \x01(\tR\n" +
	"actionType\x12;\n" +
	"\vaction_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"actionDate2\xf0\x04\n" +
	"\x0eBalanceService\x12q\n" +
	"\rCreateBalance\x121.easytrade.dbadapter.balance.CreateBalanceRequest\x1a+.easytrade.dbadapter.balance.BalanceMessage\"\x00\x12v\n" +
	"\x15GetBalanceByAccountId\x12..easytrade.dbadapter.balance.GetBalanceRequest\x1a+.easytrade.dbadapter.balance.BalanceMessage\"\x00\x12q\n" +
	"\rUpdateBalance\x121.easytrade.dbadapter.balance.UpdateBalanceRequest\x1a+.easytrade.dbadapter.balance.BalanceMessage\"\x00\x12\x80\x01\n" +
	"\x11AddBalanceHistory\x125.easytrade.dbadapter.balance.AddBalanceHistoryRequest\x1a2.easytrade.dbadapter.balance.BalanceHistoryMessage\"\x00\x12}\n" +
	"\x1dDeleteBalanceHistoryOlderThan\x12/.easytrade.dbadapter.common.DeleteBeforeRequest\x1a).easytrade.dbadapter.common.BatchResponse\"\x00B\x85\x01\n" +
	".com.dynatrace.easytrade.dbadapter.balance.grpcP\x01Z.github.com/dynatrace/easytrade/dbadapter/proto\xaa\x02 EasyTrade.DbAdapter.Balance.Grpcb\x06proto3"

var (
	file_balance_service_proto_rawDescOnce sync.Once
	file_balance_service_proto_rawDescData []byte
)

func file_balance_service_proto_rawDescGZIP() []byte {
	file_balance_service_proto_rawDescOnce.Do(func() {
		file_balance_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_balance_service_proto_rawDesc), len(file_balance_service_proto_rawDesc)))
	})
	return file_balance_service_proto_rawDescData
}

var file_balance_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_balance_service_proto_goTypes = []any{
	(*BalanceMessage)(nil),           // 0: easytrade.dbadapter.balance.BalanceMessage
	(*BalanceHistoryMessage)(nil),    // 1: easytrade.dbadapter.balance.BalanceHistoryMessage
	(*CreateBalanceRequest)(nil),     // 2: easytrade.dbadapter.balance.CreateBalanceRequest
	(*GetBalanceRequest)(nil),        // 3: easytrade.dbadapter.balance.GetBalanceRequest
	(*UpdateBalanceRequest)(nil),     // 4: easytrade.dbadapter.balance.UpdateBalanceRequest
	(*AddBalanceHistoryRequest)(nil), // 5: easytrade.dbadapter.balance.AddBalanceHistoryRequest
	(*timestamppb.Timestamp)(nil),    // 6: google.protobuf.Timestamp
	(*DeleteBeforeRequest)(nil),      // 7: easytrade.dbadapter.common.DeleteBeforeRequest
	(*BatchResponse)(nil),            // 8: easytrade.dbadapter.common.BatchResponse
}
var file_balance_service_proto_depIdxs = []int32{
	6, // 0: easytrade.dbadapter.balance.BalanceHistoryMessage.action_date:type_name -> google.protobuf.Timestamp
	6, // 1: easytrade.dbadapter.balance.AddBalanceHistoryRequest.action_date:type_name -> google.protobuf.Timestamp
	2, // 2: easytrade.dbadapter.balance.BalanceService.CreateBalance:input_type -> easytrade.dbadapter.balance.CreateBalanceRequest
	3, // 3: easytrade.dbadapter.balance.BalanceService.GetBalanceByAccountId:input_type -> easytrade.dbadapter.balance.GetBalanceRequest
	4, // 4: easytrade.dbadapter.balance.BalanceService.UpdateBalance:input_type -> easytrade.dbadapter.balance.UpdateBalanceRequest
	5, // 5: easytrade.dbadapter.balance.BalanceService.AddBalanceHistory:input_type -> easytrade.dbadapter.balance.AddBalanceHistoryRequest
	7, // 6: easytrade.dbadapter.balance.BalanceService.DeleteBalanceHistoryOlderThan:input_type -> easytrade.dbadapter.common.DeleteBeforeRequest
	0, // 7: easytrade.dbadapter.balance.BalanceService.CreateBalance:output_type -> easytrade.dbadapter.balance.BalanceMessage
	0, // 8: easytrade.dbadapter.balance.BalanceService.GetBalanceByAccountId:output_type -> easytrade.dbadapter.balance.BalanceMessage
	0, // 9: easytrade.dbadapter.balance.BalanceService.UpdateBalance:output_type -> easytrade.dbadapter.balance.BalanceMessage
	1, // 10: easytrade.dbadapter.balance.BalanceService.AddBalanceHistory:output_type -> easytrade.dbadapter.balance.BalanceHistoryMessage
	8, // 11: easytrade.dbadapter.balance.BalanceService.DeleteBalanceHistoryOlderThan:output_type -> easytrade.dbadapter.common.BatchResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_balance_service_proto_init() }
func file_balance_service_proto_init() {
	if File_balance_service_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_balance_service_proto_rawDesc), len(file_balance_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_balance_service_proto_goTypes,
		DependencyIndexes: file_balance_service_proto_depIdxs,
		MessageInfos:      file_balance_service_proto_msgTypes,
	}.Build()
	File_balance_service_proto = out.File
	file_balance_service_proto_goTypes = nil
	file_balance_service_proto_depIdxs = nil
}
