// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: credit_card_order_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CreditCardOrderService_CreateCreditCardOrder_FullMethodName         = "/easytrade.dbadapter.creditcardorder.CreditCardOrderService/CreateCreditCardOrder"
	CreditCardOrderService_GetShippingAddressByOrderId_FullMethodName   = "/easytrade.dbadapter.creditcardorder.CreditCardOrderService/GetShippingAddressByOrderId"
	CreditCardOrderService_GetStatusListByAccountId_FullMethodName      = "/easytrade.dbadapter.creditcardorder.CreditCardOrderService/GetStatusListByAccountId"
	CreditCardOrderService_GetLastOrderStatusByAccountId_FullMethodName = "/easytrade.dbadapter.creditcardorder.CreditCardOrderService/GetLastOrderStatusByAccountId"
	CreditCardOrderService_GetOrdersToManufacture_FullMethodName        = "/easytrade.dbadapter.creditcardorder.CreditCardOrderService/GetOrdersToManufacture"
	CreditCardOrderService_InsertNewStatus_FullMethodName               = "/easytrade.dbadapter.creditcardorder.CreditCardOrderService/InsertNewStatus"
	CreditCardOrderService_InsertNewCreditCard_FullMethodName           = "/easytrade.dbadapter.creditcardorder.CreditCardOrderService/InsertNewCreditCard"
	CreditCardOrderService_UpdateOrderShippingId_FullMethodName         = "/easytrade.dbadapter.creditcardorder.CreditCardOrderService/UpdateOrderShippingId"
	CreditCardOrderService_DeleteOrdersByAccountId_FullMethodName       = "/easytrade.dbadapter.creditcardorder.CreditCardOrderService/DeleteOrdersByAccountId"
)

// CreditCardOrderServiceClient is the client API for CreditCardOrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CreditCardOrderServiceClient interface {
	CreateCreditCardOrder(ctx context.Context, in *CreateCreditCardOrderRequest, opts ...grpc.CallOption) (*CreditCardOrderMessage, error)
	GetShippingAddressByOrderId(ctx context.Context, in *GetShippingAddressRequest, opts ...grpc.CallOption) (*ShippingAddressMessage, error)
	// Get all order statuses ordered by timestamp DESC
	GetStatusListByAccountId(ctx context.Context, in *GetStatusListByAccountIdRequest, opts ...grpc.CallOption) (*OrderStatusListResponse, error)
	GetLastOrderStatusByAccountId(ctx context.Context, in *GetLastOrderStatusByAccountIdRequest, opts ...grpc.CallOption) (*CreditCardOrderStatusMessage, error)
	// Get manufacture data for all orders with status ORDER_CREATED
	GetOrdersToManufacture(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*OrdersToManufactureResponse, error)
	InsertNewStatus(ctx context.Context, in *InsertNewStatusRequest, opts ...grpc.CallOption) (*CreditCardOrderStatusMessage, error)
	InsertNewCreditCard(ctx context.Context, in *InsertNewCreditCardRequest, opts ...grpc.CallOption) (*CreditCardMessage, error)
	UpdateOrderShippingId(ctx context.Context, in *UpdateOrderShippingIdRequest, opts ...grpc.CallOption) (*CreditCardOrderMessage, error)
	DeleteOrdersByAccountId(ctx context.Context, in *DeleteOrdersRequest, opts ...grpc.CallOption) (*BatchResponse, error)
}

type creditCardOrderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCreditCardOrderServiceClient(cc grpc.ClientConnInterface) CreditCardOrderServiceClient {
	return &creditCardOrderServiceClient{cc}
}

func (c *creditCardOrderServiceClient) CreateCreditCardOrder(ctx context.Context, in *CreateCreditCardOrderRequest, opts ...grpc.CallOption) (*CreditCardOrderMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreditCardOrderMessage)
	err := c.cc.Invoke(ctx, CreditCardOrderService_CreateCreditCardOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditCardOrderServiceClient) GetShippingAddressByOrderId(ctx context.Context, in *GetShippingAddressRequest, opts ...grpc.CallOption) (*ShippingAddressMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShippingAddressMessage)
	err := c.cc.Invoke(ctx, CreditCardOrderService_GetShippingAddressByOrderId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditCardOrderServiceClient) GetStatusListByAccountId(ctx context.Context, in *GetStatusListByAccountIdRequest, opts ...grpc.CallOption) (*OrderStatusListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderStatusListResponse)
	err := c.cc.Invoke(ctx, CreditCardOrderService_GetStatusListByAccountId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditCardOrderServiceClient) GetLastOrderStatusByAccountId(ctx context.Context, in *GetLastOrderStatusByAccountIdRequest, opts ...grpc.CallOption) (*CreditCardOrderStatusMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreditCardOrderStatusMessage)
	err := c.cc.Invoke(ctx, CreditCardOrderService_GetLastOrderStatusByAccountId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditCardOrderServiceClient) GetOrdersToManufacture(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*OrdersToManufactureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrdersToManufactureResponse)
	err := c.cc.Invoke(ctx, CreditCardOrderService_GetOrdersToManufacture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditCardOrderServiceClient) InsertNewStatus(ctx context.Context, in *InsertNewStatusRequest, opts ...grpc.CallOption) (*CreditCardOrderStatusMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreditCardOrderStatusMessage)
	err := c.cc.Invoke(ctx, CreditCardOrderService_InsertNewStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditCardOrderServiceClient) InsertNewCreditCard(ctx context.Context, in *InsertNewCreditCardRequest, opts ...grpc.CallOption) (*CreditCardMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreditCardMessage)
	err := c.cc.Invoke(ctx, CreditCardOrderService_InsertNewCreditCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditCardOrderServiceClient) UpdateOrderShippingId(ctx context.Context, in *UpdateOrderShippingIdRequest, opts ...grpc.CallOption) (*CreditCardOrderMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreditCardOrderMessage)
	err := c.cc.Invoke(ctx, CreditCardOrderService_UpdateOrderShippingId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditCardOrderServiceClient) DeleteOrdersByAccountId(ctx context.Context, in *DeleteOrdersRequest, opts ...grpc.CallOption) (*BatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchResponse)
	err := c.cc.Invoke(ctx, CreditCardOrderService_DeleteOrdersByAccountId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreditCardOrderServiceServer is the server API for CreditCardOrderService service.
// All implementations must embed UnimplementedCreditCardOrderServiceServer
// for forward compatibility.
type CreditCardOrderServiceServer interface {
	CreateCreditCardOrder(context.Context, *CreateCreditCardOrderRequest) (*CreditCardOrderMessage, error)
	GetShippingAddressByOrderId(context.Context, *GetShippingAddressRequest) (*ShippingAddressMessage, error)
	// Get all order statuses ordered by timestamp DESC
	GetStatusListByAccountId(context.Context, *GetStatusListByAccountIdRequest) (*OrderStatusListResponse, error)
	GetLastOrderStatusByAccountId(context.Context, *GetLastOrderStatusByAccountIdRequest) (*CreditCardOrderStatusMessage, error)
	// Get manufacture data for all orders with status ORDER_CREATED
	GetOrdersToManufacture(context.Context, *emptypb.Empty) (*OrdersToManufactureResponse, error)
	InsertNewStatus(context.Context, *InsertNewStatusRequest) (*CreditCardOrderStatusMessage, error)
	InsertNewCreditCard(context.Context, *InsertNewCreditCardRequest) (*CreditCardMessage, error)
	UpdateOrderShippingId(context.Context, *UpdateOrderShippingIdRequest) (*CreditCardOrderMessage, error)
	DeleteOrdersByAccountId(context.Context, *DeleteOrdersRequest) (*BatchResponse, error)
	mustEmbedUnimplementedCreditCardOrderServiceServer()
}

// UnimplementedCreditCardOrderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCreditCardOrderServiceServer struct{}

func (UnimplementedCreditCardOrderServiceServer) CreateCreditCardOrder(context.Context, *CreateCreditCardOrderRequest) (*CreditCardOrderMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCreditCardOrder not implemented")
}
func (UnimplementedCreditCardOrderServiceServer) GetShippingAddressByOrderId(context.Context, *GetShippingAddressRequest) (*ShippingAddressMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShippingAddressByOrderId not implemented")
}
func (UnimplementedCreditCardOrderServiceServer) GetStatusListByAccountId(context.Context, *GetStatusListByAccountIdRequest) (*OrderStatusListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatusListByAccountId not implemented")
}
func (UnimplementedCreditCardOrderServiceServer) GetLastOrderStatusByAccountId(context.Context, *GetLastOrderStatusByAccountIdRequest) (*CreditCardOrderStatusMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLastOrderStatusByAccountId not implemented")
}
func (UnimplementedCreditCardOrderServiceServer) GetOrdersToManufacture(context.Context, *emptypb.Empty) (*OrdersToManufactureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrdersToManufacture not implemented")
}
func (UnimplementedCreditCardOrderServiceServer) InsertNewStatus(context.Context, *InsertNewStatusRequest) (*CreditCardOrderStatusMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertNewStatus not implemented")
}
func (UnimplementedCreditCardOrderServiceServer) InsertNewCreditCard(context.Context, *InsertNewCreditCardRequest) (*CreditCardMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertNewCreditCard not implemented")
}
func (UnimplementedCreditCardOrderServiceServer) UpdateOrderShippingId(context.Context, *UpdateOrderShippingIdRequest) (*CreditCardOrderMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateOrderShippingId not implemented")
}
func (UnimplementedCreditCardOrderServiceServer) DeleteOrdersByAccountId(context.Context, *DeleteOrdersRequest) (*BatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteOrdersByAccountId not implemented")
}
func (UnimplementedCreditCardOrderServiceServer) mustEmbedUnimplementedCreditCardOrderServiceServer() {
}
func (UnimplementedCreditCardOrderServiceServer) testEmbeddedByValue() {}

// UnsafeCreditCardOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CreditCardOrderServiceServer will
// result in compilation errors.
type UnsafeCreditCardOrderServiceServer interface {
	mustEmbedUnimplementedCreditCardOrderServiceServer()
}

func RegisterCreditCardOrderServiceServer(s grpc.ServiceRegistrar, srv CreditCardOrderServiceServer) {
	// If the following call panics, it indicates UnimplementedCreditCardOrderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CreditCardOrderService_ServiceDesc, srv)
}

func _CreditCardOrderService_CreateCreditCardOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCreditCardOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditCardOrderServiceServer).CreateCreditCardOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditCardOrderService_CreateCreditCardOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditCardOrderServiceServer).CreateCreditCardOrder(ctx, req.(*CreateCreditCardOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditCardOrderService_GetShippingAddressByOrderId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShippingAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditCardOrderServiceServer).GetShippingAddressByOrderId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditCardOrderService_GetShippingAddressByOrderId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditCardOrderServiceServer).GetShippingAddressByOrderId(ctx, req.(*GetShippingAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditCardOrderService_GetStatusListByAccountId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusListByAccountIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditCardOrderServiceServer).GetStatusListByAccountId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditCardOrderService_GetStatusListByAccountId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditCardOrderServiceServer).GetStatusListByAccountId(ctx, req.(*GetStatusListByAccountIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditCardOrderService_GetLastOrderStatusByAccountId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastOrderStatusByAccountIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditCardOrderServiceServer).GetLastOrderStatusByAccountId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditCardOrderService_GetLastOrderStatusByAccountId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditCardOrderServiceServer).GetLastOrderStatusByAccountId(ctx, req.(*GetLastOrderStatusByAccountIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditCardOrderService_GetOrdersToManufacture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditCardOrderServiceServer).GetOrdersToManufacture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditCardOrderService_GetOrdersToManufacture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditCardOrderServiceServer).GetOrdersToManufacture(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditCardOrderService_InsertNewStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertNewStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditCardOrderServiceServer).InsertNewStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditCardOrderService_InsertNewStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditCardOrderServiceServer).InsertNewStatus(ctx, req.(*InsertNewStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditCardOrderService_InsertNewCreditCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertNewCreditCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditCardOrderServiceServer).InsertNewCreditCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditCardOrderService_InsertNewCreditCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditCardOrderServiceServer).InsertNewCreditCard(ctx, req.(*InsertNewCreditCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditCardOrderService_UpdateOrderShippingId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrderShippingIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditCardOrderServiceServer).UpdateOrderShippingId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditCardOrderService_UpdateOrderShippingId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditCardOrderServiceServer).UpdateOrderShippingId(ctx, req.(*UpdateOrderShippingIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditCardOrderService_DeleteOrdersByAccountId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditCardOrderServiceServer).DeleteOrdersByAccountId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditCardOrderService_DeleteOrdersByAccountId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditCardOrderServiceServer).DeleteOrdersByAccountId(ctx, req.(*DeleteOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CreditCardOrderService_ServiceDesc is the grpc.ServiceDesc for CreditCardOrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CreditCardOrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "easytrade.dbadapter.creditcardorder.CreditCardOrderService",
	HandlerType: (*CreditCardOrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCreditCardOrder",
			Handler:    _CreditCardOrderService_CreateCreditCardOrder_Handler,
		},
		{
			MethodName: "GetShippingAddressByOrderId",
			Handler:    _CreditCardOrderService_GetShippingAddressByOrderId_Handler,
		},
		{
			MethodName: "GetStatusListByAccountId",
			Handler:    _CreditCardOrderService_GetStatusListByAccountId_Handler,
		},
		{
			MethodName: "GetLastOrderStatusByAccountId",
			Handler:    _CreditCardOrderService_GetLastOrderStatusByAccountId_Handler,
		},
		{
			MethodName: "GetOrdersToManufacture",
			Handler:    _CreditCardOrderService_GetOrdersToManufacture_Handler,
		},
		{
			MethodName: "InsertNewStatus",
			Handler:    _CreditCardOrderService_InsertNewStatus_Handler,
		},
		{
			MethodName: "InsertNewCreditCard",
			Handler:    _CreditCardOrderService_InsertNewCreditCard_Handler,
		},
		{
			MethodName: "UpdateOrderShippingId",
			Handler:    _CreditCardOrderService_UpdateOrderShippingId_Handler,
		},
		{
			MethodName: "DeleteOrdersByAccountId",
			Handler:    _CreditCardOrderService_DeleteOrdersByAccountId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "credit_card_order_service.proto",
}
