// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: instrument_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InstrumentService_GetInstrumentById_FullMethodName     = "/easytrade.dbadapter.instrument.InstrumentService/GetInstrumentById"
	InstrumentService_GetAllInstruments_FullMethodName     = "/easytrade.dbadapter.instrument.InstrumentService/GetAllInstruments"
	InstrumentService_GetOwnedInstrument_FullMethodName    = "/easytrade.dbadapter.instrument.InstrumentService/GetOwnedInstrument"
	InstrumentService_GetOwnedInstruments_FullMethodName   = "/easytrade.dbadapter.instrument.InstrumentService/GetOwnedInstruments"
	InstrumentService_AddOwnedInstrument_FullMethodName    = "/easytrade.dbadapter.instrument.InstrumentService/AddOwnedInstrument"
	InstrumentService_UpdateOwnedInstrument_FullMethodName = "/easytrade.dbadapter.instrument.InstrumentService/UpdateOwnedInstrument"
)

// InstrumentServiceClient is the client API for InstrumentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InstrumentServiceClient interface {
	GetInstrumentById(ctx context.Context, in *GetInstrumentRequest, opts ...grpc.CallOption) (*InstrumentMessage, error)
	GetAllInstruments(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*InstrumentsResponse, error)
	GetOwnedInstrument(ctx context.Context, in *GetOwnedInstrumentRequest, opts ...grpc.CallOption) (*OwnedInstrumentMessage, error)
	// Get all owned instruments for an account
	GetOwnedInstruments(ctx context.Context, in *GetOwnedInstrumentsOfAccountRequest, opts ...grpc.CallOption) (*OwnedInstrumentsResponse, error)
	// Create a new owned instrument row and return it (with the assigned id)
	AddOwnedInstrument(ctx context.Context, in *AddOwnedInstrumentRequest, opts ...grpc.CallOption) (*OwnedInstrumentMessage, error)
	UpdateOwnedInstrument(ctx context.Context, in *UpdateOwnedInstrumentRequest, opts ...grpc.CallOption) (*OwnedInstrumentMessage, error)
}

type instrumentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInstrumentServiceClient(cc grpc.ClientConnInterface) InstrumentServiceClient {
	return &instrumentServiceClient{cc}
}

func (c *instrumentServiceClient) GetInstrumentById(ctx context.Context, in *GetInstrumentRequest, opts ...grpc.CallOption) (*InstrumentMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstrumentMessage)
	err := c.cc.Invoke(ctx, InstrumentService_GetInstrumentById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instrumentServiceClient) GetAllInstruments(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*InstrumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstrumentsResponse)
	err := c.cc.Invoke(ctx, InstrumentService_GetAllInstruments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instrumentServiceClient) GetOwnedInstrument(ctx context.Context, in *GetOwnedInstrumentRequest, opts ...grpc.CallOption) (*OwnedInstrumentMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OwnedInstrumentMessage)
	err := c.cc.Invoke(ctx, InstrumentService_GetOwnedInstrument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instrumentServiceClient) GetOwnedInstruments(ctx context.Context, in *GetOwnedInstrumentsOfAccountRequest, opts ...grpc.CallOption) (*OwnedInstrumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OwnedInstrumentsResponse)
	err := c.cc.Invoke(ctx, InstrumentService_GetOwnedInstruments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instrumentServiceClient) AddOwnedInstrument(ctx context.Context, in *AddOwnedInstrumentRequest, opts ...grpc.CallOption) (*OwnedInstrumentMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OwnedInstrumentMessage)
	err := c.cc.Invoke(ctx, InstrumentService_AddOwnedInstrument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instrumentServiceClient) UpdateOwnedInstrument(ctx context.Context, in *UpdateOwnedInstrumentRequest, opts ...grpc.CallOption) (*OwnedInstrumentMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OwnedInstrumentMessage)
	err := c.cc.Invoke(ctx, InstrumentService_UpdateOwnedInstrument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InstrumentServiceServer is the server API for InstrumentService service.
// All implementations must embed UnimplementedInstrumentServiceServer
// for forward compatibility.
type InstrumentServiceServer interface {
	GetInstrumentById(context.Context, *GetInstrumentRequest) (*InstrumentMessage, error)
	GetAllInstruments(context.Context, *emptypb.Empty) (*InstrumentsResponse, error)
	GetOwnedInstrument(context.Context, *GetOwnedInstrumentRequest) (*OwnedInstrumentMessage, error)
	// Get all owned instruments for an account
	GetOwnedInstruments(context.Context, *GetOwnedInstrumentsOfAccountRequest) (*OwnedInstrumentsResponse, error)
	// Create a new owned instrument row and return it (with the assigned id)
	AddOwnedInstrument(context.Context, *AddOwnedInstrumentRequest) (*OwnedInstrumentMessage, error)
	UpdateOwnedInstrument(context.Context, *UpdateOwnedInstrumentRequest) (*OwnedInstrumentMessage, error)
	mustEmbedUnimplementedInstrumentServiceServer()
}

// UnimplementedInstrumentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInstrumentServiceServer struct{}

func (UnimplementedInstrumentServiceServer) GetInstrumentById(context.Context, *GetInstrumentRequest) (*InstrumentMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstrumentById not implemented")
}
func (UnimplementedInstrumentServiceServer) GetAllInstruments(context.Context, *emptypb.Empty) (*InstrumentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllInstruments not implemented")
}
func (UnimplementedInstrumentServiceServer) GetOwnedInstrument(context.Context, *GetOwnedInstrumentRequest) (*OwnedInstrumentMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOwnedInstrument not implemented")
}
func (UnimplementedInstrumentServiceServer) GetOwnedInstruments(context.Context, *GetOwnedInstrumentsOfAccountRequest) (*OwnedInstrumentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOwnedInstruments not implemented")
}
func (UnimplementedInstrumentServiceServer) AddOwnedInstrument(context.Context, *AddOwnedInstrumentRequest) (*OwnedInstrumentMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method AddOwnedInstrument not implemented")
}
func (UnimplementedInstrumentServiceServer) UpdateOwnedInstrument(context.Context, *UpdateOwnedInstrumentRequest) (*OwnedInstrumentMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateOwnedInstrument not implemented")
}
func (UnimplementedInstrumentServiceServer) mustEmbedUnimplementedInstrumentServiceServer() {}
func (UnimplementedInstrumentServiceServer) testEmbeddedByValue()                           {}

// UnsafeInstrumentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InstrumentServiceServer will
// result in compilation errors.
type UnsafeInstrumentServiceServer interface {
	mustEmbedUnimplementedInstrumentServiceServer()
}

func RegisterInstrumentServiceServer(s grpc.ServiceRegistrar, srv InstrumentServiceServer) {
	// If the following call panics, it indicates UnimplementedInstrumentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InstrumentService_ServiceDesc, srv)
}

func _InstrumentService_GetInstrumentById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstrumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstrumentServiceServer).GetInstrumentById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InstrumentService_GetInstrumentById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstrumentServiceServer).GetInstrumentById(ctx, req.(*GetInstrumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstrumentService_GetAllInstruments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstrumentServiceServer).GetAllInstruments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InstrumentService_GetAllInstruments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstrumentServiceServer).GetAllInstruments(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstrumentService_GetOwnedInstrument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOwnedInstrumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstrumentServiceServer).GetOwnedInstrument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InstrumentService_GetOwnedInstrument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstrumentServiceServer).GetOwnedInstrument(ctx, req.(*GetOwnedInstrumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstrumentService_GetOwnedInstruments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOwnedInstrumentsOfAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstrumentServiceServer).GetOwnedInstruments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InstrumentService_GetOwnedInstruments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstrumentServiceServer).GetOwnedInstruments(ctx, req.(*GetOwnedInstrumentsOfAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstrumentService_AddOwnedInstrument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOwnedInstrumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstrumentServiceServer).AddOwnedInstrument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InstrumentService_AddOwnedInstrument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstrumentServiceServer).AddOwnedInstrument(ctx, req.(*AddOwnedInstrumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstrumentService_UpdateOwnedInstrument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOwnedInstrumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstrumentServiceServer).UpdateOwnedInstrument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InstrumentService_UpdateOwnedInstrument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstrumentServiceServer).UpdateOwnedInstrument(ctx, req.(*UpdateOwnedInstrumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InstrumentService_ServiceDesc is the grpc.ServiceDesc for InstrumentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InstrumentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "easytrade.dbadapter.instrument.InstrumentService",
	HandlerType: (*InstrumentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInstrumentById",
			Handler:    _InstrumentService_GetInstrumentById_Handler,
		},
		{
			MethodName: "GetAllInstruments",
			Handler:    _InstrumentService_GetAllInstruments_Handler,
		},
		{
			MethodName: "GetOwnedInstrument",
			Handler:    _InstrumentService_GetOwnedInstrument_Handler,
		},
		{
			MethodName: "GetOwnedInstruments",
			Handler:    _InstrumentService_GetOwnedInstruments_Handler,
		},
		{
			MethodName: "AddOwnedInstrument",
			Handler:    _InstrumentService_AddOwnedInstrument_Handler,
		},
		{
			MethodName: "UpdateOwnedInstrument",
			Handler:    _InstrumentService_UpdateOwnedInstrument_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "instrument_service.proto",
}
