// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: instrument_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstrumentMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstrumentMessage) Reset() {
	*x = InstrumentMessage{}
	mi := &file_instrument_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstrumentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstrumentMessage) ProtoMessage() {}

func (x *InstrumentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_instrument_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstrumentMessage.ProtoReflect.Descriptor instead.
func (*InstrumentMessage) Descriptor() ([]byte, []int) {
	return file_instrument_service_proto_rawDescGZIP(), []int{0}
}

func (x *InstrumentMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InstrumentMessage) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *InstrumentMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *InstrumentMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InstrumentMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type OwnedInstrumentMessage struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId            string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	InstrumentId         string                 `protobuf:"bytes,3,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	Quantity             float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	LastModificationDate *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_modification_date,json=lastModificationDate,proto3" json:"last_modification_date,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *OwnedInstrumentMessage) Reset() {
	*x = OwnedInstrumentMessage{}
	mi := &file_instrument_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnedInstrumentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnedInstrumentMessage) ProtoMessage() {}

func (x *OwnedInstrumentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_instrument_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnedInstrumentMessage.ProtoReflect.Descriptor instead.
func (*OwnedInstrumentMessage) Descriptor() ([]byte, []int) {
	return file_instrument_service_proto_rawDescGZIP(), []int{1}
}

func (x *OwnedInstrumentMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OwnedInstrumentMessage) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *OwnedInstrumentMessage) GetInstrumentId() string {
	if x != nil {
		return x.InstrumentId
	}
	return ""
}

func (x *OwnedInstrumentMessage) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OwnedInstrumentMessage) GetLastModificationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModificationDate
	}
	return nil
}

type GetInstrumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstrumentRequest) Reset() {
	*x = GetInstrumentRequest{}
	mi := &file_instrument_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstrumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstrumentRequest) ProtoMessage() {}

func (x *GetInstrumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_instrument_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstrumentRequest.ProtoReflect.Descriptor instead.
func (*GetInstrumentRequest) Descriptor() ([]byte, []int) {
	return file_instrument_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetInstrumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type InstrumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instruments   []*InstrumentMessage   `protobuf:"bytes,1,rep,name=instruments,proto3" json:"instruments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstrumentsResponse) Reset() {
	*x = InstrumentsResponse{}
	mi := &file_instrument_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstrumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstrumentsResponse) ProtoMessage() {}

func (x *InstrumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_instrument_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstrumentsResponse.ProtoReflect.Descriptor instead.
func (*InstrumentsResponse) Descriptor() ([]byte, []int) {
	return file_instrument_service_proto_rawDescGZIP(), []int{3}
}

func (x *InstrumentsResponse) GetInstruments() []*InstrumentMessage {
	if x != nil {
		return x.Instruments
	}
	return nil
}

type GetOwnedInstrumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	InstrumentId  string                 `protobuf:"bytes,2,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOwnedInstrumentRequest) Reset() {
	*x = GetOwnedInstrumentRequest{}
	mi := &file_instrument_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOwnedInstrumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOwnedInstrumentRequest) ProtoMessage() {}

func (x *GetOwnedInstrumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_instrument_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOwnedInstrumentRequest.ProtoReflect.Descriptor instead.
func (*GetOwnedInstrumentRequest) Descriptor() ([]byte, []int) {
	return file_instrument_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetOwnedInstrumentRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetOwnedInstrumentRequest) GetInstrumentId() string {
	if x != nil {
		return x.InstrumentId
	}
	return ""
}

type GetOwnedInstrumentsOfAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOwnedInstrumentsOfAccountRequest) Reset() {
	*x = GetOwnedInstrumentsOfAccountRequest{}
	mi := &file_instrument_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOwnedInstrumentsOfAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOwnedInstrumentsOfAccountRequest) ProtoMessage() {}

func (x *GetOwnedInstrumentsOfAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_instrument_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOwnedInstrumentsOfAccountRequest.ProtoReflect.Descriptor instead.
func (*GetOwnedInstrumentsOfAccountRequest) Descriptor() ([]byte, []int) {
	return file_instrument_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetOwnedInstrumentsOfAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type OwnedInstrumentsResponse struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	OwnedInstruments []*OwnedInstrumentMessage `protobuf:"bytes,1,rep,name=owned_instruments,json=ownedInstruments,proto3" json:"owned_instruments,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OwnedInstrumentsResponse) Reset() {
	*x = OwnedInstrumentsResponse{}
	mi := &file_instrument_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnedInstrumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnedInstrumentsResponse) ProtoMessage() {}

func (x *OwnedInstrumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_instrument_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnedInstrumentsResponse.ProtoReflect.Descriptor instead.
func (*OwnedInstrumentsResponse) Descriptor() ([]byte, []int) {
	return file_instrument_service_proto_rawDescGZIP(), []int{6}
}

func (x *OwnedInstrumentsResponse) GetOwnedInstruments() []*OwnedInstrumentMessage {
	if x != nil {
		return x.OwnedInstruments
	}
	return nil
}

type AddOwnedInstrumentRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AccountId            string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	InstrumentId         string                 `protobuf:"bytes,2,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	Quantity             float64                `protobuf:"fixed64,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	LastModificationDate *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_modification_date,json=lastModificationDate,proto3" json:"last_modification_date,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AddOwnedInstrumentRequest) Reset() {
	*x = AddOwnedInstrumentRequest{}
	mi := &file_instrument_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOwnedInstrumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOwnedInstrumentRequest) ProtoMessage() {}

func (x *AddOwnedInstrumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_instrument_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOwnedInstrumentRequest.ProtoReflect.Descriptor instead.
func (*AddOwnedInstrumentRequest) Descriptor() ([]byte, []int) {
	return file_instrument_service_proto_rawDescGZIP(), []int{7}
}

func (x *AddOwnedInstrumentRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AddOwnedInstrumentRequest) GetInstrumentId() string {
	if x != nil {
		return x.InstrumentId
	}
	return ""
}

func (x *AddOwnedInstrumentRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AddOwnedInstrumentRequest) GetLastModificationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModificationDate
	}
	return nil
}

type UpdateOwnedInstrumentRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId            string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	InstrumentId         string                 `protobuf:"bytes,3,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	Quantity             float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	LastModificationDate *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_modification_date,json=lastModificationDate,proto3" json:"last_modification_date,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateOwnedInstrumentRequest) Reset() {
	*x = UpdateOwnedInstrumentRequest{}
	mi := &file_instrument_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOwnedInstrumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOwnedInstrumentRequest) ProtoMessage() {}

func (x *UpdateOwnedInstrumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_instrument_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOwnedInstrumentRequest.ProtoReflect.Descriptor instead.
func (*UpdateOwnedInstrumentRequest) Descriptor() ([]byte, []int) {
	return file_instrument_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateOwnedInstrumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateOwnedInstrumentRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UpdateOwnedInstrumentRequest) GetInstrumentId() string {
	if x != nil {
		return x.InstrumentId
	}
	return ""
}

func (x *UpdateOwnedInstrumentRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *UpdateOwnedInstrumentRequest) GetLastModificationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModificationDate
	}
	return nil
}

var File_instrument_service_proto protoreflect.FileDescriptor

const file_instrument_service_proto_rawDesc = "" +
	"\n" +
	"\x18instrument_service.proto\x12\x1eeasytrade.dbadapter.instrument\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\x01\n" +
	"\x11InstrumentMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"\xda\x01\n" +
	"\x16OwnedInstrumentMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12#\n" +
	"\rinstrument_id\x18\x03 \x01(\tR\finstrumentId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12P\n" +
	"\x16last_modification_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x14lastModificationDate\"&\n" +
	"\x14GetInstrumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"j\n" +
	"\x13InstrumentsResponse\x12S\n" +
	"\vinstruments\x18\x01 \x03(\v21.easytrade.dbadapter.instrument.InstrumentMessageR\vinstruments\"_\n" +
	"\x19GetOwnedInstrumentRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12#\n" +
	"\rinstrument_id\x18\x02 \x01(\tR\finstrumentId\"D\n" +
	"#GetOwnedInstrumentsOfAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"\x7f\n" +
	"\x18OwnedInstrumentsResponse\x12c\n" +
	"\x11owned_instruments\x18\x01 \x03(\v26.easytrade.dbadapter.instrument.OwnedInstrumentMessageR\x10ownedInstruments\"\xcd\x01\n" +
	"\x19AddOwnedInstrumentRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12#\n" +
	"\rinstrument_id\x18\x02 \x01(\tR\finstrumentId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x01R\bquantity\x12P\n" +
	"\x16last_modification_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x14lastModificationDate\"\xe0\x01\n" +
	"\x1cUpdateOwnedInstrumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12#\n" +
	"\rinstrument_id\x18\x03 \x01(\tR\finstrumentId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12P\n" +
	"\x16last_modification_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x14lastModificationDate2\xba\x06\n" +
	"\x11InstrumentService\x12~\n" +
	"\x11GetInstrumentById\x124.easytrade.dbadapter.instrument.GetInstrumentRequest\x1a1.easytrade.dbadapter.instrument.InstrumentMessage\"\x00\x12b\n" +
	"\x11GetAllInstruments\x12\x16.google.protobuf.Empty\x1a3.easytrade.dbadapter.instrument.InstrumentsResponse\"\x00\x12\x89\x01\n" +
	"\x12GetOwnedInstrument\x129.easytrade.dbadapter.instrument.GetOwnedInstrumentRequest\x1a6.easytrade.dbadapter.instrument.OwnedInstrumentMessage\"\x00\x12\x96\x01\n" +
	"\x13GetOwnedInstruments\x12C.easytrade.dbadapter.instrument.GetOwnedInstrumentsOfAccountRequest\x1a8.easytrade.dbadapter.instrument.OwnedInstrumentsResponse\"\x00\x12\x89\x01\n" +
	"\x12AddOwnedInstrument\x129.easytrade.dbadapter.instrument.AddOwnedInstrumentRequest\x1a6.easytrade.dbadapter.instrument.OwnedInstrumentMessage\"\x00\x12\x8f\x01\n" +
	"\x15UpdateOwnedInstrument\x12<.easytrade.dbadapter.instrument.UpdateOwnedInstrumentRequest\x1a6.easytrade.dbadapter.instrument.OwnedInstrumentMessage\"\x00B\x8b\x01\n" +
	"1com.dynatrace.easytrade.dbadapter.instrument.grpcP\x01Z.github.com/dynatrace/easytrade/dbadapter/proto\xaa\x02#EasyTrade.DbAdapter.Instrument.Grpcb\x06proto3"

var (
	file_instrument_service_proto_rawDescOnce sync.Once
	file_instrument_service_proto_rawDescData []byte
)

func file_instrument_service_proto_rawDescGZIP() []byte {
	file_instrument_service_proto_rawDescOnce.Do(func() {
		file_instrument_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_instrument_service_proto_rawDesc), len(file_instrument_service_proto_rawDesc)))
	})
	return file_instrument_service_proto_rawDescData
}

var file_instrument_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_instrument_service_proto_goTypes = []any{
	(*InstrumentMessage)(nil),                   // 0: easytrade.dbadapter.instrument.InstrumentMessage
	(*OwnedInstrumentMessage)(nil),              // 1: easytrade.dbadapter.instrument.OwnedInstrumentMessage
	(*GetInstrumentRequest)(nil),                // 2: easytrade.dbadapter.instrument.GetInstrumentRequest
	(*InstrumentsResponse)(nil),                 // 3: easytrade.dbadapter.instrument.InstrumentsResponse
	(*GetOwnedInstrumentRequest)(nil),           // 4: easytrade.dbadapter.instrument.GetOwnedInstrumentRequest
	(*GetOwnedInstrumentsOfAccountRequest)(nil), // 5: easytrade.dbadapter.instrument.GetOwnedInstrumentsOfAccountRequest
	(*OwnedInstrumentsResponse)(nil),            // 6: easytrade.dbadapter.instrument.OwnedInstrumentsResponse
	(*AddOwnedInstrumentRequest)(nil),           // 7: easytrade.dbadapter.instrument.AddOwnedInstrumentRequest
	(*UpdateOwnedInstrumentRequest)(nil),        // 8: easytrade.dbadapter.instrument.UpdateOwnedInstrumentRequest
	(*timestamppb.Timestamp)(nil),               // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                       // 10: google.protobuf.Empty
}
var file_instrument_service_proto_depIdxs = []int32{
	9,  // 0: easytrade.dbadapter.instrument.OwnedInstrumentMessage.last_modification_date:type_name -> google.protobuf.Timestamp
	0,  // 1: easytrade.dbadapter.instrument.InstrumentsResponse.instruments:type_name -> easytrade.dbadapter.instrument.InstrumentMessage
	1,  // 2: easytrade.dbadapter.instrument.OwnedInstrumentsResponse.owned_instruments:type_name -> easytrade.dbadapter.instrument.OwnedInstrumentMessage
	9,  // 3: easytrade.dbadapter.instrument.AddOwnedInstrumentRequest.last_modification_date:type_name -> google.protobuf.Timestamp
	9,  // 4: easytrade.dbadapter.instrument.UpdateOwnedInstrumentRequest.last_modification_date:type_name -> google.protobuf.Timestamp
	2,  // 5: easytrade.dbadapter.instrument.InstrumentService.GetInstrumentById:input_type -> easytrade.dbadapter.instrument.GetInstrumentRequest
	10, // 6: easytrade.dbadapter.instrument.InstrumentService.GetAllInstruments:input_type -> google.protobuf.Empty
	4,  // 7: easytrade.dbadapter.instrument.InstrumentService.GetOwnedInstrument:input_type -> easytrade.dbadapter.instrument.GetOwnedInstrumentRequest
	5,  // 8: easytrade.dbadapter.instrument.InstrumentService.GetOwnedInstruments:input_type -> easytrade.dbadapter.instrument.GetOwnedInstrumentsOfAccountRequest
	7,  // 9: easytrade.dbadapter.instrument.InstrumentService.AddOwnedInstrument:input_type -> easytrade.dbadapter.instrument.AddOwnedInstrumentRequest
	8,  // 10: easytrade.dbadapter.instrument.InstrumentService.UpdateOwnedInstrument:input_type -> easytrade.dbadapter.instrument.UpdateOwnedInstrumentRequest
	0,  // 11: easytrade.dbadapter.instrument.InstrumentService.GetInstrumentById:output_type -> easytrade.dbadapter.instrument.InstrumentMessage
	3,  // 12: easytrade.dbadapter.instrument.InstrumentService.GetAllInstruments:output_type -> easytrade.dbadapter.instrument.InstrumentsResponse
	1,  // 13: easytrade.dbadapter.instrument.InstrumentService.GetOwnedInstrument:output_type -> easytrade.dbadapter.instrument.OwnedInstrumentMessage
	6,  // 14: easytrade.dbadapter.instrument.InstrumentService.GetOwnedInstruments:output_type -> easytrade.dbadapter.instrument.OwnedInstrumentsResponse
	1,  // 15: easytrade.dbadapter.instrument.InstrumentService.AddOwnedInstrument:output_type -> easytrade.dbadapter.instrument.OwnedInstrumentMessage
	1,  // 16: easytrade.dbadapter.instrument.InstrumentService.UpdateOwnedInstrument:output_type -> easytrade.dbadapter.instrument.OwnedInstrumentMessage
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_instrument_service_proto_init() }
func file_instrument_service_proto_init() {
	if File_instrument_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_instrument_service_proto_rawDesc), len(file_instrument_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_instrument_service_proto_goTypes,
		DependencyIndexes: file_instrument_service_proto_depIdxs,
		MessageInfos:      file_instrument_service_proto_msgTypes,
	}.Build()
	File_instrument_service_proto = out.File
	file_instrument_service_proto_goTypes = nil
	file_instrument_service_proto_depIdxs = nil
}
