// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: package_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PackageMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Support       string                 `protobuf:"bytes,4,opt,name=support,proto3" json:"support,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageMessage) Reset() {
	*x = PackageMessage{}
	mi := &file_package_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageMessage) ProtoMessage() {}

func (x *PackageMessage) ProtoReflect() protoreflect.Message {
	mi := &file_package_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageMessage.ProtoReflect.Descriptor instead.
func (*PackageMessage) Descriptor() ([]byte, []int) {
	return file_package_service_proto_rawDescGZIP(), []int{0}
}

func (x *PackageMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PackageMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PackageMessage) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PackageMessage) GetSupport() string {
	if x != nil {
		return x.Support
	}
	return ""
}

type PackagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packages      []*PackageMessage      `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackagesResponse) Reset() {
	*x = PackagesResponse{}
	mi := &file_package_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackagesResponse) ProtoMessage() {}

func (x *PackagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_package_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackagesResponse.ProtoReflect.Descriptor instead.
func (*PackagesResponse) Descriptor() ([]byte, []int) {
	return file_package_service_proto_rawDescGZIP(), []int{1}
}

func (x *PackagesResponse) GetPackages() []*PackageMessage {
	if x != nil {
		return x.Packages
	}
	return nil
}

var File_package_service_proto protoreflect.FileDescriptor

const file_package_service_proto_rawDesc = "" +
	"\n" +
	"\x15package_service.proto\x12\x1beasytrade.dbadapter.package\x1a\x1bgoogle/protobuf/empty.proto\"d\n" +
	"\x0ePackageMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x18\n" +
	"\asupport\x18\x04 \x01(\tR\asupport\"[\n" +
	"\x10PackagesResponse\x12G\n" +
	"\bpackages\x18\x01 \x03(\v2+.easytrade.dbadapter.package.PackageMessageR\bpackages2h\n" +
	"\x0ePackageService\x12V\n" +
	"\vGetPackages\x12\x16.google.protobuf.Empty\x1a-.easytrade.dbadapter.package.PackagesResponse\"\x00B\x85\x01\n" +
	".com.dynatrace.easytrade.dbadapter.package.grpcP\x01Z.github.com/dynatrace/easytrade/dbadapter/proto\xaa\x02 EasyTrade.DbAdapter.Package.Grpcb\x06proto3"

var (
	file_package_service_proto_rawDescOnce sync.Once
	file_package_service_proto_rawDescData []byte
)

func file_package_service_proto_rawDescGZIP() []byte {
	file_package_service_proto_rawDescOnce.Do(func() {
		file_package_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_package_service_proto_rawDesc), len(file_package_service_proto_rawDesc)))
	})
	return file_package_service_proto_rawDescData
}

var file_package_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_package_service_proto_goTypes = []any{
	(*PackageMessage)(nil),   // 0: easytrade.dbadapter.package.PackageMessage
	(*PackagesResponse)(nil), // 1: easytrade.dbadapter.package.PackagesResponse
	(*emptypb.Empty)(nil),    // 2: google.protobuf.Empty
}
var file_package_service_proto_depIdxs = []int32{
	0, // 0: easytrade.dbadapter.package.PackagesResponse.packages:type_name -> easytrade.dbadapter.package.PackageMessage
	2, // 1: easytrade.dbadapter.package.PackageService.GetPackages:input_type -> google.protobuf.Empty
	1, // 2: easytrade.dbadapter.package.PackageService.GetPackages:output_type -> easytrade.dbadapter.package.PackagesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_package_service_proto_init() }
func file_package_service_proto_init() {
	if File_package_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_package_service_proto_rawDesc), len(file_package_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_package_service_proto_goTypes,
		DependencyIndexes: file_package_service_proto_depIdxs,
		MessageInfos:      file_package_service_proto_msgTypes,
	}.Build()
	File_package_service_proto = out.File
	file_package_service_proto_goTypes = nil
	file_package_service_proto_depIdxs = nil
}
