// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: trade_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TradeService_CreateTrade_FullMethodName           = "/easytrade.dbadapter.trade.TradeService/CreateTrade"
	TradeService_UpdateTrade_FullMethodName           = "/easytrade.dbadapter.trade.TradeService/UpdateTrade"
	TradeService_GetOpenTrades_FullMethodName         = "/easytrade.dbadapter.trade.TradeService/GetOpenTrades"
	TradeService_GetExpiredTrades_FullMethodName      = "/easytrade.dbadapter.trade.TradeService/GetExpiredTrades"
	TradeService_GetAccountTrades_FullMethodName      = "/easytrade.dbadapter.trade.TradeService/GetAccountTrades"
	TradeService_DeleteTradesOlderThan_FullMethodName = "/easytrade.dbadapter.trade.TradeService/DeleteTradesOlderThan"
)

// TradeServiceClient is the client API for TradeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TradeServiceClient interface {
	CreateTrade(ctx context.Context, in *CreateTradeRequest, opts ...grpc.CallOption) (*TradeMessage, error)
	UpdateTrade(ctx context.Context, in *UpdateTradeRequest, opts ...grpc.CallOption) (*TradeMessage, error)
	// Get all open trades (trade_closed = false)
	GetOpenTrades(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TradesResponse, error)
	// Get expired open trades (trade_closed = false AND timestamp_close < now)
	GetExpiredTrades(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TradesResponse, error)
	// Get all trades for a specific account with optional filters
	GetAccountTrades(ctx context.Context, in *GetAccountTradesRequest, opts ...grpc.CallOption) (*TradesResponse, error)
	DeleteTradesOlderThan(ctx context.Context, in *DeleteBeforeRequest, opts ...grpc.CallOption) (*BatchResponse, error)
}

type tradeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTradeServiceClient(cc grpc.ClientConnInterface) TradeServiceClient {
	return &tradeServiceClient{cc}
}

func (c *tradeServiceClient) CreateTrade(ctx context.Context, in *CreateTradeRequest, opts ...grpc.CallOption) (*TradeMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TradeMessage)
	err := c.cc.Invoke(ctx, TradeService_CreateTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeServiceClient) UpdateTrade(ctx context.Context, in *UpdateTradeRequest, opts ...grpc.CallOption) (*TradeMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TradeMessage)
	err := c.cc.Invoke(ctx, TradeService_UpdateTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeServiceClient) GetOpenTrades(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TradesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TradesResponse)
	err := c.cc.Invoke(ctx, TradeService_GetOpenTrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeServiceClient) GetExpiredTrades(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TradesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TradesResponse)
	err := c.cc.Invoke(ctx, TradeService_GetExpiredTrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeServiceClient) GetAccountTrades(ctx context.Context, in *GetAccountTradesRequest, opts ...grpc.CallOption) (*TradesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TradesResponse)
	err := c.cc.Invoke(ctx, TradeService_GetAccountTrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeServiceClient) DeleteTradesOlderThan(ctx context.Context, in *DeleteBeforeRequest, opts ...grpc.CallOption) (*BatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchResponse)
	err := c.cc.Invoke(ctx, TradeService_DeleteTradesOlderThan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradeServiceServer is the server API for TradeService service.
// All implementations must embed UnimplementedTradeServiceServer
// for forward compatibility.
type TradeServiceServer interface {
	CreateTrade(context.Context, *CreateTradeRequest) (*TradeMessage, error)
	UpdateTrade(context.Context, *UpdateTradeRequest) (*TradeMessage, error)
	// Get all open trades (trade_closed = false)
	GetOpenTrades(context.Context, *emptypb.Empty) (*TradesResponse, error)
	// Get expired open trades (trade_closed = false AND timestamp_close < now)
	GetExpiredTrades(context.Context, *emptypb.Empty) (*TradesResponse, error)
	// Get all trades for a specific account with optional filters
	GetAccountTrades(context.Context, *GetAccountTradesRequest) (*TradesResponse, error)
	DeleteTradesOlderThan(context.Context, *DeleteBeforeRequest) (*BatchResponse, error)
	mustEmbedUnimplementedTradeServiceServer()
}

// UnimplementedTradeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTradeServiceServer struct{}

func (UnimplementedTradeServiceServer) CreateTrade(context.Context, *CreateTradeRequest) (*TradeMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTrade not implemented")
}
func (UnimplementedTradeServiceServer) UpdateTrade(context.Context, *UpdateTradeRequest) (*TradeMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTrade not implemented")
}
func (UnimplementedTradeServiceServer) GetOpenTrades(context.Context, *emptypb.Empty) (*TradesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOpenTrades not implemented")
}
func (UnimplementedTradeServiceServer) GetExpiredTrades(context.Context, *emptypb.Empty) (*TradesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExpiredTrades not implemented")
}
func (UnimplementedTradeServiceServer) GetAccountTrades(context.Context, *GetAccountTradesRequest) (*TradesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccountTrades not implemented")
}
func (UnimplementedTradeServiceServer) DeleteTradesOlderThan(context.Context, *DeleteBeforeRequest) (*BatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTradesOlderThan not implemented")
}
func (UnimplementedTradeServiceServer) mustEmbedUnimplementedTradeServiceServer() {}
func (UnimplementedTradeServiceServer) testEmbeddedByValue()                      {}

// UnsafeTradeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradeServiceServer will
// result in compilation errors.
type UnsafeTradeServiceServer interface {
	mustEmbedUnimplementedTradeServiceServer()
}

func RegisterTradeServiceServer(s grpc.ServiceRegistrar, srv TradeServiceServer) {
	// If the following call panics, it indicates UnimplementedTradeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TradeService_ServiceDesc, srv)
}

func _TradeService_CreateTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServiceServer).CreateTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeService_CreateTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServiceServer).CreateTrade(ctx, req.(*CreateTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeService_UpdateTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServiceServer).UpdateTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeService_UpdateTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServiceServer).UpdateTrade(ctx, req.(*UpdateTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeService_GetOpenTrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServiceServer).GetOpenTrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeService_GetOpenTrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServiceServer).GetOpenTrades(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeService_GetExpiredTrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServiceServer).GetExpiredTrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeService_GetExpiredTrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServiceServer).GetExpiredTrades(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeService_GetAccountTrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountTradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServiceServer).GetAccountTrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeService_GetAccountTrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServiceServer).GetAccountTrades(ctx, req.(*GetAccountTradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeService_DeleteTradesOlderThan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBeforeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServiceServer).DeleteTradesOlderThan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeService_DeleteTradesOlderThan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServiceServer).DeleteTradesOlderThan(ctx, req.(*DeleteBeforeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TradeService_ServiceDesc is the grpc.ServiceDesc for TradeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TradeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "easytrade.dbadapter.trade.TradeService",
	HandlerType: (*TradeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTrade",
			Handler:    _TradeService_CreateTrade_Handler,
		},
		{
			MethodName: "UpdateTrade",
			Handler:    _TradeService_UpdateTrade_Handler,
		},
		{
			MethodName: "GetOpenTrades",
			Handler:    _TradeService_GetOpenTrades_Handler,
		},
		{
			MethodName: "GetExpiredTrades",
			Handler:    _TradeService_GetExpiredTrades_Handler,
		},
		{
			MethodName: "GetAccountTrades",
			Handler:    _TradeService_GetAccountTrades_Handler,
		},
		{
			MethodName: "DeleteTradesOlderThan",
			Handler:    _TradeService_DeleteTradesOlderThan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trade_service.proto",
}
