// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: trade_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TradeMessage struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId           string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	InstrumentId        string                 `protobuf:"bytes,3,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	Direction           string                 `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
	Quantity            float64                `protobuf:"fixed64,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	EntryPrice          float64                `protobuf:"fixed64,6,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	TimestampOpen       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp_open,json=timestampOpen,proto3" json:"timestamp_open,omitempty"`
	TimestampClose      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp_close,json=timestampClose,proto3" json:"timestamp_close,omitempty"`
	TradeClosed         bool                   `protobuf:"varint,9,opt,name=trade_closed,json=tradeClosed,proto3" json:"trade_closed,omitempty"`
	TransactionHappened bool                   `protobuf:"varint,10,opt,name=transaction_happened,json=transactionHappened,proto3" json:"transaction_happened,omitempty"`
	Status              string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TradeMessage) Reset() {
	*x = TradeMessage{}
	mi := &file_trade_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeMessage) ProtoMessage() {}

func (x *TradeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_trade_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeMessage.ProtoReflect.Descriptor instead.
func (*TradeMessage) Descriptor() ([]byte, []int) {
	return file_trade_service_proto_rawDescGZIP(), []int{0}
}

func (x *TradeMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TradeMessage) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *TradeMessage) GetInstrumentId() string {
	if x != nil {
		return x.InstrumentId
	}
	return ""
}

func (x *TradeMessage) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *TradeMessage) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *TradeMessage) GetEntryPrice() float64 {
	if x != nil {
		return x.EntryPrice
	}
	return 0
}

func (x *TradeMessage) GetTimestampOpen() *timestamppb.Timestamp {
	if x != nil {
		return x.TimestampOpen
	}
	return nil
}

func (x *TradeMessage) GetTimestampClose() *timestamppb.Timestamp {
	if x != nil {
		return x.TimestampClose
	}
	return nil
}

func (x *TradeMessage) GetTradeClosed() bool {
	if x != nil {
		return x.TradeClosed
	}
	return false
}

func (x *TradeMessage) GetTransactionHappened() bool {
	if x != nil {
		return x.TransactionHappened
	}
	return false
}

func (x *TradeMessage) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateTradeRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AccountId           string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	InstrumentId        string                 `protobuf:"bytes,2,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	Direction           string                 `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"`
	Quantity            float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	EntryPrice          float64                `protobuf:"fixed64,5,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	TimestampOpen       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp_open,json=timestampOpen,proto3" json:"timestamp_open,omitempty"`
	TimestampClose      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp_close,json=timestampClose,proto3" json:"timestamp_close,omitempty"`
	TradeClosed         bool                   `protobuf:"varint,8,opt,name=trade_closed,json=tradeClosed,proto3" json:"trade_closed,omitempty"`
	TransactionHappened bool                   `protobuf:"varint,9,opt,name=transaction_happened,json=transactionHappened,proto3" json:"transaction_happened,omitempty"`
	Status              string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateTradeRequest) Reset() {
	*x = CreateTradeRequest{}
	mi := &file_trade_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTradeRequest) ProtoMessage() {}

func (x *CreateTradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trade_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTradeRequest.ProtoReflect.Descriptor instead.
func (*CreateTradeRequest) Descriptor() ([]byte, []int) {
	return file_trade_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTradeRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateTradeRequest) GetInstrumentId() string {
	if x != nil {
		return x.InstrumentId
	}
	return ""
}

func (x *CreateTradeRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *CreateTradeRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateTradeRequest) GetEntryPrice() float64 {
	if x != nil {
		return x.EntryPrice
	}
	return 0
}

func (x *CreateTradeRequest) GetTimestampOpen() *timestamppb.Timestamp {
	if x != nil {
		return x.TimestampOpen
	}
	return nil
}

func (x *CreateTradeRequest) GetTimestampClose() *timestamppb.Timestamp {
	if x != nil {
		return x.TimestampClose
	}
	return nil
}

func (x *CreateTradeRequest) GetTradeClosed() bool {
	if x != nil {
		return x.TradeClosed
	}
	return false
}

func (x *CreateTradeRequest) GetTransactionHappened() bool {
	if x != nil {
		return x.TransactionHappened
	}
	return false
}

func (x *CreateTradeRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateTradeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TimestampClose *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp_close,json=timestampClose,proto3" json:"timestamp_close,omitempty"`
	TradeClosed    bool                   `protobuf:"varint,3,opt,name=trade_closed,json=tradeClosed,proto3" json:"trade_closed,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateTradeRequest) Reset() {
	*x = UpdateTradeRequest{}
	mi := &file_trade_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTradeRequest) ProtoMessage() {}

func (x *UpdateTradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trade_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTradeRequest.ProtoReflect.Descriptor instead.
func (*UpdateTradeRequest) Descriptor() ([]byte, []int) {
	return file_trade_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTradeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTradeRequest) GetTimestampClose() *timestamppb.Timestamp {
	if x != nil {
		return x.TimestampClose
	}
	return nil
}

func (x *UpdateTradeRequest) GetTradeClosed() bool {
	if x != nil {
		return x.TradeClosed
	}
	return false
}

func (x *UpdateTradeRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetAccountTradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	OnlyOpen      bool                   `protobuf:"varint,2,opt,name=only_open,json=onlyOpen,proto3" json:"only_open,omitempty"`
	OnlyLong      bool                   `protobuf:"varint,3,opt,name=only_long,json=onlyLong,proto3" json:"only_long,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountTradesRequest) Reset() {
	*x = GetAccountTradesRequest{}
	mi := &file_trade_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountTradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountTradesRequest) ProtoMessage() {}

func (x *GetAccountTradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trade_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountTradesRequest.ProtoReflect.Descriptor instead.
func (*GetAccountTradesRequest) Descriptor() ([]byte, []int) {
	return file_trade_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetAccountTradesRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetAccountTradesRequest) GetOnlyOpen() bool {
	if x != nil {
		return x.OnlyOpen
	}
	return false
}

func (x *GetAccountTradesRequest) GetOnlyLong() bool {
	if x != nil {
		return x.OnlyLong
	}
	return false
}

type TradesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trades        []*TradeMessage        `protobuf:"bytes,1,rep,name=trades,proto3" json:"trades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradesResponse) Reset() {
	*x = TradesResponse{}
	mi := &file_trade_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradesResponse) ProtoMessage() {}

func (x *TradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trade_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradesResponse.ProtoReflect.Descriptor instead.
func (*TradesResponse) Descriptor() ([]byte, []int) {
	return file_trade_service_proto_rawDescGZIP(), []int{4}
}

func (x *TradesResponse) GetTrades() []*TradeMessage {
	if x != nil {
		return x.Trades
	}
	return nil
}

var File_trade_service_proto protoreflect.FileDescriptor

const file_trade_service_proto_rawDesc = "" +
	"\n" +
	"\x13trade_service.proto\x12\x19easytrade.dbadapter.trade\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\"\xb3\x03\n" +
	"\fTradeMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12#\n" +
	"\rinstrument_id\x18\x03 \x01(\tR\finstrumentId\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\tR\tdirection\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x01R\bquantity\x12\x1f\n" +
	"\ventry_price\x18\x06 \x01(\x01R\n" +
	"entryPrice\x12A\n" +
	"\x0etimestamp_open\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\rtimestampOpen\x12C\n" +
	"\x0ftimestamp_close\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x0etimestampClose\x12!\n" +
	"\ftrade_closed\x18\t \x01(\bR\vtradeClosed\x121\n" +
	"\x14transaction_happened\x18\n" +
	" \x01(\bR\x13transactionHappened\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\"\xa9\x03\n" +
	"\x12CreateTradeRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12#\n" +
	"\rinstrument_id\x18\x02 \x01(\tR\finstrumentId\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\tR\tdirection\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12\x1f\n" +
	"\ventry_price\x18\x05 \x01(\x01R\n" +
	"entryPrice\x12A\n" +
	"\x0etimestamp_open\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\rtimestampOpen\x12C\n" +
	"\x0ftimestamp_close\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0etimestampClose\x12!\n" +
	"\ftrade_closed\x18\b \x01(\bR\vtradeClosed\x121\n" +
	"\x14transaction_happened\x18\t \x01(\bR\x13transactionHappened\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\"\xa4\x01\n" +
	"\x12UpdateTradeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12C\n" +
	"\x0ftimestamp_close\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0etimestampClose\x12!\n" +
	"\ftrade_closed\x18\x03 \x01(\bR\vtradeClosed\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"r\n" +
	"\x17GetAccountTradesRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1b\n" +
	"\tonly_open\x18\x02 \x01(\bR\bonlyOpen\x12\x1b\n" +
	"\tonly_long\x18\x03 \x01(\bR\bonlyLong\"Q\n" +
	"\x0eTradesResponse\x12?\n" +
	"\x06trades\x18\x01 \x03(\v2'.easytrade.dbadapter.trade.TradeMessageR\x06trades2\xfb\x04\n" +
	"\fTradeService\x12g\n" +
	"\vCreateTrade\x12-.easytrade.dbadapter.trade.CreateTradeRequest\x1a'.easytrade.dbadapter.trade.TradeMessage\"\x00\x12g\n" +
	"\vUpdateTrade\x12-.easytrade.dbadapter.trade.UpdateTradeRequest\x1a'.easytrade.dbadapter.trade.TradeMessage\"\x00\x12T\n" +
	"\rGetOpenTrades\x12\x16.google.protobuf.Empty\x1a).easytrade.dbadapter.trade.TradesResponse\"\x00\x12W\n" +
	"\x10GetExpiredTrades\x12\x16.google.protobuf.Empty\x1a).easytrade.dbadapter.trade.TradesResponse\"\x00\x12s\n" +
	"\x10GetAccountTrades\x122.easytrade.dbadapter.trade.GetAccountTradesRequest\x1a).easytrade.dbadapter.trade.TradesResponse\"\x00\x12u\n" +
	"\x15DeleteTradesOlderThan\x12/.easytrade.dbadapter.common.DeleteBeforeRequest\x1a).easytrade.dbadapter.common.BatchResponse\"\x00B\x81\x01\n" +
	",com.dynatrace.easytrade.dbadapter.trade.grpcP\x01Z.github.com/dynatrace/easytrade/dbadapter/proto\xaa\x02\x1eEasyTrade.DbAdapter.Trade.Grpcb\x06proto3"

var (
	file_trade_service_proto_rawDescOnce sync.Once
	file_trade_service_proto_rawDescData []byte
)

func file_trade_service_proto_rawDescGZIP() []byte {
	file_trade_service_proto_rawDescOnce.Do(func() {
		file_trade_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trade_service_proto_rawDesc), len(file_trade_service_proto_rawDesc)))
	})
	return file_trade_service_proto_rawDescData
}

var file_trade_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_trade_service_proto_goTypes = []any{
	(*TradeMessage)(nil),            // 0: easytrade.dbadapter.trade.TradeMessage
	(*CreateTradeRequest)(nil),      // 1: easytrade.dbadapter.trade.CreateTradeRequest
	(*UpdateTradeRequest)(nil),      // 2: easytrade.dbadapter.trade.UpdateTradeRequest
	(*GetAccountTradesRequest)(nil), // 3: easytrade.dbadapter.trade.GetAccountTradesRequest
	(*TradesResponse)(nil),          // 4: easytrade.dbadapter.trade.TradesResponse
	(*timestamppb.Timestamp)(nil),   // 5: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 6: google.protobuf.Empty
	(*DeleteBeforeRequest)(nil),     // 7: easytrade.dbadapter.common.DeleteBeforeRequest
	(*BatchResponse)(nil),           // 8: easytrade.dbadapter.common.BatchResponse
}
var file_trade_service_proto_depIdxs = []int32{
	5,  // 0: easytrade.dbadapter.trade.TradeMessage.timestamp_open:type_name -> google.protobuf.Timestamp
	5,  // 1: easytrade.dbadapter.trade.TradeMessage.timestamp_close:type_name -> google.protobuf.Timestamp
	5,  // 2: easytrade.dbadapter.trade.CreateTradeRequest.timestamp_open:type_name -> google.protobuf.Timestamp
	5,  // 3: easytrade.dbadapter.trade.CreateTradeRequest.timestamp_close:type_name -> google.protobuf.Timestamp
	5,  // 4: easytrade.dbadapter.trade.UpdateTradeRequest.timestamp_close:type_name -> google.protobuf.Timestamp
	0,  // 5: easytrade.dbadapter.trade.TradesResponse.trades:type_name -> easytrade.dbadapter.trade.TradeMessage
	1,  // 6: easytrade.dbadapter.trade.TradeService.CreateTrade:input_type -> easytrade.dbadapter.trade.CreateTradeRequest
	2,  // 7: easytrade.dbadapter.trade.TradeService.UpdateTrade:input_type -> easytrade.dbadapter.trade.UpdateTradeRequest
	6,  // 8: easytrade.dbadapter.trade.TradeService.GetOpenTrades:input_type -> google.protobuf.Empty
	6,  // 9: easytrade.dbadapter.trade.TradeService.GetExpiredTrades:input_type -> google.protobuf.Empty
	3,  // 10: easytrade.dbadapter.trade.TradeService.GetAccountTrades:input_type -> easytrade.dbadapter.trade.GetAccountTradesRequest
	7,  // 11: easytrade.dbadapter.trade.TradeService.DeleteTradesOlderThan:input_type -> easytrade.dbadapter.common.DeleteBeforeRequest
	0,  // 12: easytrade.dbadapter.trade.TradeService.CreateTrade:output_type -> easytrade.dbadapter.trade.TradeMessage
	0,  // 13: easytrade.dbadapter.trade.TradeService.UpdateTrade:output_type -> easytrade.dbadapter.trade.TradeMessage
	4,  // 14: easytrade.dbadapter.trade.TradeService.GetOpenTrades:output_type -> easytrade.dbadapter.trade.TradesResponse
	4,  // 15: easytrade.dbadapter.trade.TradeService.GetExpiredTrades:output_type -> easytrade.dbadapter.trade.TradesResponse
	4,  // 16: easytrade.dbadapter.trade.TradeService.GetAccountTrades:output_type -> easytrade.dbadapter.trade.TradesResponse
	8,  // 17: easytrade.dbadapter.trade.TradeService.DeleteTradesOlderThan:output_type -> easytrade.dbadapter.common.BatchResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_trade_service_proto_init() }
func file_trade_service_proto_init() {
	if File_trade_service_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trade_service_proto_rawDesc), len(file_trade_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trade_service_proto_goTypes,
		DependencyIndexes: file_trade_service_proto_depIdxs,
		MessageInfos:      file_trade_service_proto_msgTypes,
	}.Build()
	File_trade_service_proto = out.File
	file_trade_service_proto_goTypes = nil
	file_trade_service_proto_depIdxs = nil
}
