name: "Build and Push Docker Images"
description: "Build Docker images using docker compose and optionally push to registry"
inputs:
  push:
    description: "Whether to push images to registry"
    required: false
    default: "false"
  tag:
    description: "Tag for all Docker images"
    required: true
  push-latest:
    description: "Whether to also push images with 'latest' tag"
    required: false
    default: "false"
  registry:
    description: "Docker registry URL"
    required: false
    default: "europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade"
  compose-file:
    description: "Path to docker compose file"
    required: false
    default: "compose.build.yaml"
  artifact-dir:
    description: "Directory to store build artifacts"
    required: false
  artifact-name:
    description: "Name of the uploaded artifact"
    required: false
outputs:
  images:
    description: "List of built images"
    value: ${{ steps.build.outputs.images }}
  artifact-dir:
    description: "Directory containing build artifacts"
    value: ${{ steps.artifacts.outputs.artifact-dir }}
  artifact-name:
    description: "Name of the uploaded artifact"
    value: ${{ inputs.artifact-name }}

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker images
      id: build
      shell: bash
      env:
        REGISTRY: ${{ inputs.registry }}
        TAG: ${{ inputs.tag }}
      run: |
        echo "Building images with tag: $TAG"
        docker compose -f ${{ inputs.compose-file }} build

        # List built images
        IMAGES=$(docker compose -f ${{ inputs.compose-file }} config --services | tr '\n' ',' | sed 's/,$//')
        echo "images=$IMAGES" >> $GITHUB_OUTPUT
        echo "Built images: $IMAGES"

    - name: Push Docker images
      if: inputs.push == 'true'
      shell: bash
      env:
        REGISTRY: ${{ inputs.registry }}
        TAG: ${{ inputs.tag }}
      run: |
        echo "Pushing images to registry..."
        docker compose -f ${{ inputs.compose-file }} push
        echo "Successfully pushed all images with tag: $TAG"

    - name: Push Docker images with latest tag
      if: inputs.push == 'true' && inputs.push-latest == 'true'
      shell: bash
      env:
        REGISTRY: ${{ inputs.registry }}
        TAG: ${{ inputs.tag }}
      run: |
        echo "Pushing images with latest to registry..."
        images=$(docker compose -f ${{ inputs.compose-file }} config --images)
        for image in $images; do
          image_name=$(echo "$image" | cut -d: -f1)
          docker tag "${image}" "${image_name}":latest
          docker push "${image_name}":latest
        done
        echo "Push $TAG as new latest completed."

    - name: Prepare build artifacts
      if: inputs.artifact-dir
      id: artifacts
      shell: bash
      env:
        TAG: ${{ inputs.tag }}
        REGISTRY: ${{ inputs.registry }}
        ARTIFACT_DIR: ${{ inputs.artifact-dir }}
      run: |
        mkdir -p $ARTIFACT_DIR
        envsubst < compose.yaml > $ARTIFACT_DIR/compose.yaml
        echo "artifact-dir=$ARTIFACT_DIR" >> $GITHUB_OUTPUT

    - name: Upload build artifacts
      if: inputs.artifact-dir
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.artifact-dir }}
        if-no-files-found: error
