name: "Build and Push Docker Images"
description: "Build Docker images using docker compose and optionally push to registry"
inputs:
  push:
    description: "Whether to push images to registry"
    required: false
    default: "false"
  tag:
    description: "Tag for all Docker images"
    required: true
  push-latest:
    description: "Whether to also push images with 'latest' tag"
    required: false
    default: "false"
  registry:
    description: "Docker registry URL"
    required: false
    default: "ghcr.io/arctiqdynatracedemo/easytrade"
  compose-file:
    description: "Path to docker compose file"
    required: false
    default: "compose.build.yaml"
  image:
    description: image to build
    required: true
outputs:
  images:
    description: "List of built images"
    value: ${{ steps.build.outputs.images }}
  artifact-dir:
    description: "Directory containing build artifacts"
    value: ${{ steps.artifacts.outputs.artifact-dir }}
  artifact-name:
    description: "Name of the uploaded artifact"
    value: ${{ inputs.artifact-name }}

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker images
      id: build
      shell: bash
      env:
        REGISTRY: ${{ inputs.registry }}
        TAG: ${{ inputs.tag }}
      run: |
        echo "Building image ${{ inputs.image }} with tag: $TAG"
        docker compose -f ${{ inputs.compose-file }} build ${{ inputs.image }}

    - name: Push Docker images
      if: inputs.push == 'true'
      shell: bash
      env:
        REGISTRY: ${{ inputs.registry }}
        TAG: ${{ inputs.tag }}
      run: |
        echo "Pushing images to registry..."
        docker compose -f ${{ inputs.compose-file }} push ${{ inputs.image }}
        echo "Successfully pushed all images with tag: $TAG"
