name: "Build and Push Docker Images"
description: "Build Docker images using docker compose and optionally push to registry"
inputs:
  push:
    description: "Whether to push images to registry"
    required: false
    default: "false"
  tag:
    description: "Tag for all Docker images"
    required: true
  push-latest:
    description: "Whether to also push images with 'latest' tag"
    required: false
    default: "false"
  registry:
    description: "Docker registry URL"
    required: false
    default: "europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade"
  compose-file:
    description: "Path to docker compose file"
    required: false
    default: "compose.build.yaml"
  service:
    description: "Single service to build/push. Leave empty to build/push all services in the compose file"
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Retrieve GAR credentials
      if: inputs.push == 'true'
      shell: bash
      run: |
        echo "$GAR_CREDENTIALS" | docker login -u _json_key_base64 --password-stdin europe-docker.pkg.dev

    - name: Build Docker images
      shell: bash
      env:
        REGISTRY: ${{ inputs.registry }}
        TAG: ${{ inputs.tag }}
      run: |
        echo "Building images with tag: $TAG"
        docker compose -f ${{ inputs.compose-file }} build --build-arg GIT_COMMIT="$GITHUB_SHA" --build-arg GIT_ORIGIN="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" ${{ inputs.service }}

    - name: Push Docker images
      if: inputs.push == 'true'
      shell: bash
      env:
        REGISTRY: ${{ inputs.registry }}
        TAG: ${{ inputs.tag }}
      run: |
        echo "Pushing images to registry..."
        docker compose -f ${{ inputs.compose-file }} push ${{ inputs.service }}
        echo "Successfully pushed all images with tag: $TAG"

    - name: Push Docker images with latest tag
      if: inputs.push == 'true' && inputs.push-latest == 'true'
      shell: bash
      env:
        REGISTRY: ${{ inputs.registry }}
        TAG: ${{ inputs.tag }}
      run: |
        echo "Pushing images with latest to registry..."
        images=$(docker compose -f ${{ inputs.compose-file }} config --images ${{ inputs.service }})
        for image in $images; do
          image_name=$(echo "$image" | cut -d: -f1)
          docker tag "${image}" "${image_name}":latest
          docker push "${image_name}":latest
        done
        echo "Push $TAG as new latest completed."
