{{- if not .Values.global.existingSecret }}
{{- $db := .Values.global.database }}
{{- $dbPassword := $db.password }}
{{- $dbName := $db.name }}
{{- $dbType := $db.type }}
{{- $dbHost := printf "%s-db" $.Release.Name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-connection-strings
  labels:
    {{- include "easytrade.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if eq $dbType "postgres" }}
  DB_URL: {{ printf "postgres://postgres:%s@%s:5432/%s?sslmode=disable" ($dbPassword | urlquery) $dbHost $dbName | quote }}
  {{- else }}
  DB_URL: {{ printf "sqlserver://sa:%s@%s:1433?database=%s&encrypt=disable" ($dbPassword | urlquery) $dbHost $dbName | quote }}
  {{- end }}
{{- end }}