{{- $db := .Values.global.database }}
{{- $dbHost := printf "%s-db" .Release.Name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-connection-strings
  labels:
    {{- include "easytrade.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if eq $db.type "postgres" }}
  DB_URL: {{ printf "postgres://postgres:%s@%s:%d/%s?sslmode=disable" ($db.password | urlquery) $dbHost ($db.port | int) $db.name | quote }}
  {{- else }}
  DB_URL: {{ printf "sqlserver://sa:%s@%s:%d?database=%s&encrypt=disable" ($db.password | urlquery) $dbHost ($db.port | int) $db.name | quote }}
  {{- end }}