{{- if not .Values.global.database.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-password
  labels:
    {{- include "easytrade.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.global.database.password | quote }}
{{- end }}
