apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountservice
spec:
  selector:
    matchLabels:
      app: accountservice
  template:
    metadata:
      labels:
        app: accountservice
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
        - name: accountservice
          image: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/accountservice:d863a2e
          ports:
            - containerPort: 8080
          env:
            - name: MANAGER_HOSTANDPORT
              value: "manager:80"
            - name: PROXY_PREFIX
              value: "accountservice"
          resources:
            requests:
              cpu: 150m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: accountservice
spec:
  type: ClusterIP
  selector:
    app: accountservice
  ports:
    - name: http
      port: 8080
      targetPort: 8080
