apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregator-service-envs
data:
  OFFER_SERVICE_PROTOCOL: "http"
  OFFER_SERVICE_HOST: "offerservice"
  OFFER_SERVICE_PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-service
spec:
  selector:
    matchLabels:
      app: aggregator-service
  template:
    metadata:
      labels:
        app: aggregator-service
    spec:
      containers:
        - name: aggregator-service
          image: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/aggregator-service:8831949
          env: []
          envFrom:
            - configMapRef:
                name: aggregator-service-envs
          resources:
            requests:
              cpu: 10m
              memory: 30Mi
            limits:
              memory: 30Mi
