apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-service-envs
data:
  ACCOUNTSERVICE_HOSTANDPORT: "accountservice:8080"
  PRICINGSERVICE_HOSTANDPORT: "pricing-service:8080"
  ENGINE_HOSTANDPORT: "engine:8080"
  PROXY_PREFIX: "broker-service"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-service
spec:
  selector:
    matchLabels:
      app: broker-service
  template:
    metadata:
      labels:
        app: broker-service
    spec:
      containers:
        - name: broker-service
          image: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/broker-service:d863a2e
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: broker-service-envs
            - configMapRef:
                name: feature-flag-service-setup
          env:
            - name: MSSQL_CONNECTIONSTRING
              valueFrom:
                configMapKeyRef:
                  name: connection-strings
                  key: DOTNET_CONNECTION_STRING
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: broker-service
spec:
  type: ClusterIP
  selector:
    app: broker-service
  ports:
    - name: http
      port: 80
      targetPort: 80
