apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculationservice
spec:
  selector:
    matchLabels:
      app: calculationservice
  template:
    metadata:
      labels:
        app: calculationservice
    spec:
      containers:
        - name: calculationservice
          image: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/calculationservice:d863a2e
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
