apiVersion: apps/v1
kind: Deployment
metadata:
  name: contentcreator
spec:
  selector:
    matchLabels:
      app: contentcreator
  template:
    metadata:
      labels:
        app: contentcreator
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
        - name: contentcreator
          image: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/contentcreator:d863a2e
          env:
            - name: MSSQL_CONNECTIONSTRING
              valueFrom:
                configMapKeyRef:
                  name: connection-strings
                  key: JAVA_CONNECTION_STRING
          resources:
            requests:
              cpu: 150m
              memory: 200Mi
