apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-flag-service
spec:
  selector:
    matchLabels:
      app: feature-flag-service
  template:
    metadata:
      labels:
        app: feature-flag-service
    spec:
      containers:
        - name: feature-flag-service
          image: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/feature-flag-service:4d5adb3
          ports:
            - containerPort: 8080
          env: []
          resources:
            requests:
              cpu: 30m
              memory: 600Mi
            limits:
              memory: 600Mi
---
apiVersion: v1
kind: Service
metadata:
  name: feature-flag-service
spec:
  type: ClusterIP
  selector:
    app: feature-flag-service
  ports:
    - name: feature-flag-service
      port: 8080
      targetPort: 8080
