apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/frontend:1ccb463
          ports:
            - containerPort: 3000
          env: []
          resources:
            requests:
              cpu: 30m
              memory: 100Mi
            limits:
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
