apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendreverseproxy
spec:
  selector:
    matchLabels:
      app: frontendreverseproxy
  template:
    metadata:
      labels:
        app: frontendreverseproxy
    spec:
      containers:
        - name: frontendreverseproxy
          image: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/frontendreverseproxy:8831949
          ports:
            - containerPort: 80
          env: []
          resources:
            requests:
              cpu: 50m
              memory: 75Mi
            limits:
              memory: 75Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontendreverseproxy-easytrade
  # Uncomment the annotations block to allow the service
  # to be exposed publicly if deployed on EKS
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: frontendreverseproxy
  ports:
    - name: http
      port: 80
      targetPort: 80
