apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loadgen
  name: loadgen
spec:
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      labels:
        app: loadgen
    spec:
      containers:
        - name: loadgen
          image: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/loadgen:d863a2e
          imagePullPolicy: Always
          env:
            - name: EASYTRADE_URL
              value: "http://frontendreverseproxy-easytrade"
            - name: RARE_VISITS_INTERVAL_MINUTES
              value: "60"
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
