apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginservice
spec:
  selector:
    matchLabels:
      app: loginservice
  template:
    metadata:
      labels:
        app: loginservice
    spec:
      containers:
        - name: loginservice
          image: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/loginservice:d863a2e
          ports:
            - containerPort: 80
          env:
            - name: PROXY_PREFIX
              value: "loginservice"
            - name: MSSQL_CONNECTIONSTRING
              valueFrom:
                configMapKeyRef:
                  name: connection-strings
                  key: DOTNET_CONNECTION_STRING
          resources:
            requests:
              cpu: 100m
              memory: 350Mi
---
apiVersion: v1
kind: Service
metadata:
  name: loginservice
spec:
  type: ClusterIP
  selector:
    app: loginservice
  ports:
    - name: http
      port: 80
      targetPort: 80
