apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginservice
spec:
  selector:
    matchLabels:
      app: loginservice
  template:
    metadata:
      labels:
        app: loginservice
    spec:
      containers:
        - name: loginservice
          image: gcr.io/dynatrace-demoability/easytrade/loginservice:44e1877
          ports:
            - containerPort: 80
          env:
            - name: MSSQL_CONNECTIONSTRING
              value: "Data Source=db;Initial Catalog=TradeManagement;Persist Security Info=True;User ID=sa;Password=yourStrong(!)Password;TrustServerCertificate=true"
          resources:
            requests:
              cpu: 100m
              memory: 350Mi
---
apiVersion: v1
kind: Service
metadata:
  name: loginservice
spec:
  type: ClusterIP
  selector:
    app: loginservice
  ports:
    - name: http
      port: 80
      targetPort: 80
