apiVersion: v1
kind: ConfigMap
metadata:
  name: offerservice-envs
data:
  LOGIN_SERVICE_PORT: '80'
  LOGIN_SERVICE_BASE_URL: loginservice
  MANAGER_BASE_URL: manager
  MANAGER_PORT: '80'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: offerservice
spec:
  selector:
    matchLabels:
      app: offerservice
  template:
    metadata:
      labels:
        app: offerservice
    spec:
      containers:
        - name: offerservice
          image: gcr.io/dynatrace-demoability/easytrade/offerservice:f505fb9
          ports:
            - containerPort: 8080
          envFrom:
          - configMapRef:
              name: offerservice-envs
          - configMapRef:
              name: flagsmith-setup
          resources:
            requests:
              cpu: 300m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: offerservice
spec:
  type: ClusterIP
  selector:
    app: offerservice
  ports:
    - name: http
      port: 8080
      targetPort: 8080