apiVersion: v1
kind: ConfigMap
metadata:
  name: offerservice-envs
data:
  LOGIN_SERVICE_PORT: "80"
  LOGIN_SERVICE_BASE_URL: loginservice
  MANAGER_BASE_URL: manager
  MANAGER_PORT: "80"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: offerservice
spec:
  selector:
    matchLabels:
      app: offerservice
  template:
    metadata:
      labels:
        app: offerservice
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "true"
    spec:
      containers:
        - name: offerservice
          image: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/offerservice:d863a2e
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: offerservice-envs
            - configMapRef:
                name: feature-flag-service-setup
          resources:
            requests:
              cpu: 300m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: offerservice
spec:
  type: ClusterIP
  selector:
    app: offerservice
  ports:
    - name: http
      port: 8080
      targetPort: 8080
