apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricingservice
spec:
  selector:
    matchLabels:
      app: pricingservice
  template:
    metadata:
      labels:
        app: pricingservice
    spec:
      containers:
        - name: pricingservice
          image: gcr.io/dynatrace-demoability/easytrade/pricingservice:44e1877
          ports:
            - containerPort: 80
          env:
            - name: MANAGER_HOSTANDPORT
              value: "manager:80"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_USER
              value: "userxxx"
            - name: RABBITMQ_PASSWORD
              value: "passxxx"
          resources:
            requests:
              cpu: 100m
              memory: 350Mi
---
apiVersion: v1
kind: Service
metadata:
  name: pricingservice
spec:
  type: ClusterIP
  selector:
    app: pricingservice
  ports:
    - name: http
      port: 80
      targetPort: 80
