apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/rabbitmq:8831949
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env: []
          resources:
            requests:
              cpu: 10m
              memory: 175Mi
            limits:
              memory: 175Mi
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - name: rabbitmq-listener
      port: 5672
      targetPort: 5672
    - name: rabbitmq-ui
      port: 15672
      targetPort: 15672
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-vars
data:
  RABBITMQ_USER: userxxx
  RABBITMQ_PASSWORD: passxxx
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  RABBITMQ_QUEUE: Trade_Data_Raw
