apiVersion: apps/v1
kind: Deployment
metadata:
  name: third-party-service
spec:
  selector:
    matchLabels:
      app: third-party-service
  template:
    metadata:
      labels:
        app: third-party-service
    spec:
      containers:
        - name: third-party-service
          image: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/third-party-service:8831949
          ports:
            - containerPort: 8080
          env:
            - name: CREDIT_CARD_ORDER_SERVICE_HOSTANDPORT
              value: "credit-card-order-service:8080"
            - name: PROXY_PREFIX
              value: "third-party-service"
            - name: COURIER_DELAY
              value: "400"
            - name: COURIER_RATE
              value: "900"
            - name: MANUFACTURE_DELAY
              value: "500"
            - name: MANUFACTURE_RATE
              value: "900"
          envFrom:
            - configMapRef:
                name: feature-flag-service-setup
          resources:
            requests:
              cpu: 10m
              memory: 300Mi
            limits:
              memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: third-party-service
spec:
  type: ClusterIP
  selector:
    app: third-party-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
