configs:
  - id: app_easytrade
    config:
      name: EasyTrade
      template: app_easytrade.json
      skip: false
    type:
      settings:
        schema: builtin:management-zones
        scope: environment
