// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: balance_service.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace EasyTrade.DbAdapter.Balance.Grpc {
  public static partial class BalanceService
  {
    static readonly string __ServiceName = "easytrade.dbadapter.balance.BalanceService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::EasyTrade.DbAdapter.Balance.Grpc.CreateBalanceRequest> __Marshaller_easytrade_dbadapter_balance_CreateBalanceRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::EasyTrade.DbAdapter.Balance.Grpc.CreateBalanceRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::EasyTrade.DbAdapter.Balance.Grpc.BalanceMessage> __Marshaller_easytrade_dbadapter_balance_BalanceMessage = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::EasyTrade.DbAdapter.Balance.Grpc.BalanceMessage.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::EasyTrade.DbAdapter.Balance.Grpc.GetBalanceRequest> __Marshaller_easytrade_dbadapter_balance_GetBalanceRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::EasyTrade.DbAdapter.Balance.Grpc.GetBalanceRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::EasyTrade.DbAdapter.Balance.Grpc.UpdateBalanceRequest> __Marshaller_easytrade_dbadapter_balance_UpdateBalanceRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::EasyTrade.DbAdapter.Balance.Grpc.UpdateBalanceRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::EasyTrade.DbAdapter.Balance.Grpc.AddBalanceHistoryRequest> __Marshaller_easytrade_dbadapter_balance_AddBalanceHistoryRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::EasyTrade.DbAdapter.Balance.Grpc.AddBalanceHistoryRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::EasyTrade.DbAdapter.Balance.Grpc.BalanceHistoryMessage> __Marshaller_easytrade_dbadapter_balance_BalanceHistoryMessage = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::EasyTrade.DbAdapter.Balance.Grpc.BalanceHistoryMessage.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::EasyTrade.DbAdapter.Common.Grpc.DeleteBeforeRequest> __Marshaller_easytrade_dbadapter_common_DeleteBeforeRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::EasyTrade.DbAdapter.Common.Grpc.DeleteBeforeRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::EasyTrade.DbAdapter.Common.Grpc.BatchResponse> __Marshaller_easytrade_dbadapter_common_BatchResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::EasyTrade.DbAdapter.Common.Grpc.BatchResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::EasyTrade.DbAdapter.Balance.Grpc.CreateBalanceRequest, global::EasyTrade.DbAdapter.Balance.Grpc.BalanceMessage> __Method_CreateBalance = new grpc::Method<global::EasyTrade.DbAdapter.Balance.Grpc.CreateBalanceRequest, global::EasyTrade.DbAdapter.Balance.Grpc.BalanceMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateBalance",
        __Marshaller_easytrade_dbadapter_balance_CreateBalanceRequest,
        __Marshaller_easytrade_dbadapter_balance_BalanceMessage);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::EasyTrade.DbAdapter.Balance.Grpc.GetBalanceRequest, global::EasyTrade.DbAdapter.Balance.Grpc.BalanceMessage> __Method_GetBalanceByAccountId = new grpc::Method<global::EasyTrade.DbAdapter.Balance.Grpc.GetBalanceRequest, global::EasyTrade.DbAdapter.Balance.Grpc.BalanceMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetBalanceByAccountId",
        __Marshaller_easytrade_dbadapter_balance_GetBalanceRequest,
        __Marshaller_easytrade_dbadapter_balance_BalanceMessage);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::EasyTrade.DbAdapter.Balance.Grpc.UpdateBalanceRequest, global::EasyTrade.DbAdapter.Balance.Grpc.BalanceMessage> __Method_UpdateBalance = new grpc::Method<global::EasyTrade.DbAdapter.Balance.Grpc.UpdateBalanceRequest, global::EasyTrade.DbAdapter.Balance.Grpc.BalanceMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateBalance",
        __Marshaller_easytrade_dbadapter_balance_UpdateBalanceRequest,
        __Marshaller_easytrade_dbadapter_balance_BalanceMessage);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::EasyTrade.DbAdapter.Balance.Grpc.AddBalanceHistoryRequest, global::EasyTrade.DbAdapter.Balance.Grpc.BalanceHistoryMessage> __Method_AddBalanceHistory = new grpc::Method<global::EasyTrade.DbAdapter.Balance.Grpc.AddBalanceHistoryRequest, global::EasyTrade.DbAdapter.Balance.Grpc.BalanceHistoryMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddBalanceHistory",
        __Marshaller_easytrade_dbadapter_balance_AddBalanceHistoryRequest,
        __Marshaller_easytrade_dbadapter_balance_BalanceHistoryMessage);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::EasyTrade.DbAdapter.Common.Grpc.DeleteBeforeRequest, global::EasyTrade.DbAdapter.Common.Grpc.BatchResponse> __Method_DeleteBalanceHistoryOlderThan = new grpc::Method<global::EasyTrade.DbAdapter.Common.Grpc.DeleteBeforeRequest, global::EasyTrade.DbAdapter.Common.Grpc.BatchResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteBalanceHistoryOlderThan",
        __Marshaller_easytrade_dbadapter_common_DeleteBeforeRequest,
        __Marshaller_easytrade_dbadapter_common_BatchResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::EasyTrade.DbAdapter.Balance.Grpc.BalanceServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of BalanceService</summary>
    [grpc::BindServiceMethod(typeof(BalanceService), "BindService")]
    public abstract partial class BalanceServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::EasyTrade.DbAdapter.Balance.Grpc.BalanceMessage> CreateBalance(global::EasyTrade.DbAdapter.Balance.Grpc.CreateBalanceRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::EasyTrade.DbAdapter.Balance.Grpc.BalanceMessage> GetBalanceByAccountId(global::EasyTrade.DbAdapter.Balance.Grpc.GetBalanceRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::EasyTrade.DbAdapter.Balance.Grpc.BalanceMessage> UpdateBalance(global::EasyTrade.DbAdapter.Balance.Grpc.UpdateBalanceRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::EasyTrade.DbAdapter.Balance.Grpc.BalanceHistoryMessage> AddBalanceHistory(global::EasyTrade.DbAdapter.Balance.Grpc.AddBalanceHistoryRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::EasyTrade.DbAdapter.Common.Grpc.BatchResponse> DeleteBalanceHistoryOlderThan(global::EasyTrade.DbAdapter.Common.Grpc.DeleteBeforeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for BalanceService</summary>
    public partial class BalanceServiceClient : grpc::ClientBase<BalanceServiceClient>
    {
      /// <summary>Creates a new client for BalanceService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public BalanceServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for BalanceService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public BalanceServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected BalanceServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected BalanceServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EasyTrade.DbAdapter.Balance.Grpc.BalanceMessage CreateBalance(global::EasyTrade.DbAdapter.Balance.Grpc.CreateBalanceRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateBalance(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EasyTrade.DbAdapter.Balance.Grpc.BalanceMessage CreateBalance(global::EasyTrade.DbAdapter.Balance.Grpc.CreateBalanceRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateBalance, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EasyTrade.DbAdapter.Balance.Grpc.BalanceMessage> CreateBalanceAsync(global::EasyTrade.DbAdapter.Balance.Grpc.CreateBalanceRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateBalanceAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EasyTrade.DbAdapter.Balance.Grpc.BalanceMessage> CreateBalanceAsync(global::EasyTrade.DbAdapter.Balance.Grpc.CreateBalanceRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateBalance, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EasyTrade.DbAdapter.Balance.Grpc.BalanceMessage GetBalanceByAccountId(global::EasyTrade.DbAdapter.Balance.Grpc.GetBalanceRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetBalanceByAccountId(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EasyTrade.DbAdapter.Balance.Grpc.BalanceMessage GetBalanceByAccountId(global::EasyTrade.DbAdapter.Balance.Grpc.GetBalanceRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetBalanceByAccountId, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EasyTrade.DbAdapter.Balance.Grpc.BalanceMessage> GetBalanceByAccountIdAsync(global::EasyTrade.DbAdapter.Balance.Grpc.GetBalanceRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetBalanceByAccountIdAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EasyTrade.DbAdapter.Balance.Grpc.BalanceMessage> GetBalanceByAccountIdAsync(global::EasyTrade.DbAdapter.Balance.Grpc.GetBalanceRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetBalanceByAccountId, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EasyTrade.DbAdapter.Balance.Grpc.BalanceMessage UpdateBalance(global::EasyTrade.DbAdapter.Balance.Grpc.UpdateBalanceRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateBalance(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EasyTrade.DbAdapter.Balance.Grpc.BalanceMessage UpdateBalance(global::EasyTrade.DbAdapter.Balance.Grpc.UpdateBalanceRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateBalance, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EasyTrade.DbAdapter.Balance.Grpc.BalanceMessage> UpdateBalanceAsync(global::EasyTrade.DbAdapter.Balance.Grpc.UpdateBalanceRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateBalanceAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EasyTrade.DbAdapter.Balance.Grpc.BalanceMessage> UpdateBalanceAsync(global::EasyTrade.DbAdapter.Balance.Grpc.UpdateBalanceRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateBalance, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EasyTrade.DbAdapter.Balance.Grpc.BalanceHistoryMessage AddBalanceHistory(global::EasyTrade.DbAdapter.Balance.Grpc.AddBalanceHistoryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddBalanceHistory(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EasyTrade.DbAdapter.Balance.Grpc.BalanceHistoryMessage AddBalanceHistory(global::EasyTrade.DbAdapter.Balance.Grpc.AddBalanceHistoryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddBalanceHistory, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EasyTrade.DbAdapter.Balance.Grpc.BalanceHistoryMessage> AddBalanceHistoryAsync(global::EasyTrade.DbAdapter.Balance.Grpc.AddBalanceHistoryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddBalanceHistoryAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EasyTrade.DbAdapter.Balance.Grpc.BalanceHistoryMessage> AddBalanceHistoryAsync(global::EasyTrade.DbAdapter.Balance.Grpc.AddBalanceHistoryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddBalanceHistory, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EasyTrade.DbAdapter.Common.Grpc.BatchResponse DeleteBalanceHistoryOlderThan(global::EasyTrade.DbAdapter.Common.Grpc.DeleteBeforeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteBalanceHistoryOlderThan(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EasyTrade.DbAdapter.Common.Grpc.BatchResponse DeleteBalanceHistoryOlderThan(global::EasyTrade.DbAdapter.Common.Grpc.DeleteBeforeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteBalanceHistoryOlderThan, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EasyTrade.DbAdapter.Common.Grpc.BatchResponse> DeleteBalanceHistoryOlderThanAsync(global::EasyTrade.DbAdapter.Common.Grpc.DeleteBeforeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteBalanceHistoryOlderThanAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EasyTrade.DbAdapter.Common.Grpc.BatchResponse> DeleteBalanceHistoryOlderThanAsync(global::EasyTrade.DbAdapter.Common.Grpc.DeleteBeforeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteBalanceHistoryOlderThan, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override BalanceServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new BalanceServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(BalanceServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CreateBalance, serviceImpl.CreateBalance)
          .AddMethod(__Method_GetBalanceByAccountId, serviceImpl.GetBalanceByAccountId)
          .AddMethod(__Method_UpdateBalance, serviceImpl.UpdateBalance)
          .AddMethod(__Method_AddBalanceHistory, serviceImpl.AddBalanceHistory)
          .AddMethod(__Method_DeleteBalanceHistoryOlderThan, serviceImpl.DeleteBalanceHistoryOlderThan).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, BalanceServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CreateBalance, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EasyTrade.DbAdapter.Balance.Grpc.CreateBalanceRequest, global::EasyTrade.DbAdapter.Balance.Grpc.BalanceMessage>(serviceImpl.CreateBalance));
      serviceBinder.AddMethod(__Method_GetBalanceByAccountId, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EasyTrade.DbAdapter.Balance.Grpc.GetBalanceRequest, global::EasyTrade.DbAdapter.Balance.Grpc.BalanceMessage>(serviceImpl.GetBalanceByAccountId));
      serviceBinder.AddMethod(__Method_UpdateBalance, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EasyTrade.DbAdapter.Balance.Grpc.UpdateBalanceRequest, global::EasyTrade.DbAdapter.Balance.Grpc.BalanceMessage>(serviceImpl.UpdateBalance));
      serviceBinder.AddMethod(__Method_AddBalanceHistory, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EasyTrade.DbAdapter.Balance.Grpc.AddBalanceHistoryRequest, global::EasyTrade.DbAdapter.Balance.Grpc.BalanceHistoryMessage>(serviceImpl.AddBalanceHistory));
      serviceBinder.AddMethod(__Method_DeleteBalanceHistoryOlderThan, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EasyTrade.DbAdapter.Common.Grpc.DeleteBeforeRequest, global::EasyTrade.DbAdapter.Common.Grpc.BatchResponse>(serviceImpl.DeleteBalanceHistoryOlderThan));
    }

  }
}
#endregion
