// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: trade_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EasyTrade.DbAdapter.Trade.Grpc {

  /// <summary>Holder for reflection information generated from trade_service.proto</summary>
  public static partial class TradeServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for trade_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TradeServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChN0cmFkZV9zZXJ2aWNlLnByb3RvEhllYXN5dHJhZGUuZGJhZGFwdGVyLnRy",
            "YWRlGhtnb29nbGUvcHJvdG9idWYvZW1wdHkucHJvdG8aH2dvb2dsZS9wcm90",
            "b2J1Zi90aW1lc3RhbXAucHJvdG8aDGNvbW1vbi5wcm90byKsAgoMVHJhZGVN",
            "ZXNzYWdlEgoKAmlkGAEgASgJEhIKCmFjY291bnRfaWQYAiABKAkSFQoNaW5z",
            "dHJ1bWVudF9pZBgDIAEoCRIRCglkaXJlY3Rpb24YBCABKAkSEAoIcXVhbnRp",
            "dHkYBSABKAESEwoLZW50cnlfcHJpY2UYBiABKAESMgoOdGltZXN0YW1wX29w",
            "ZW4YByABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEjMKD3RpbWVz",
            "dGFtcF9jbG9zZRgIIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAS",
            "FAoMdHJhZGVfY2xvc2VkGAkgASgIEhwKFHRyYW5zYWN0aW9uX2hhcHBlbmVk",
            "GAogASgIEg4KBnN0YXR1cxgLIAEoCSKmAgoSQ3JlYXRlVHJhZGVSZXF1ZXN0",
            "EhIKCmFjY291bnRfaWQYASABKAkSFQoNaW5zdHJ1bWVudF9pZBgCIAEoCRIR",
            "CglkaXJlY3Rpb24YAyABKAkSEAoIcXVhbnRpdHkYBCABKAESEwoLZW50cnlf",
            "cHJpY2UYBSABKAESMgoOdGltZXN0YW1wX29wZW4YBiABKAsyGi5nb29nbGUu",
            "cHJvdG9idWYuVGltZXN0YW1wEjMKD3RpbWVzdGFtcF9jbG9zZRgHIAEoCzIa",
            "Lmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASFAoMdHJhZGVfY2xvc2VkGAgg",
            "ASgIEhwKFHRyYW5zYWN0aW9uX2hhcHBlbmVkGAkgASgIEg4KBnN0YXR1cxgK",
            "IAEoCSJ7ChJVcGRhdGVUcmFkZVJlcXVlc3QSCgoCaWQYASABKAkSMwoPdGlt",
            "ZXN0YW1wX2Nsb3NlGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFt",
            "cBIUCgx0cmFkZV9jbG9zZWQYAyABKAgSDgoGc3RhdHVzGAQgASgJIlMKF0dl",
            "dEFjY291bnRUcmFkZXNSZXF1ZXN0EhIKCmFjY291bnRfaWQYASABKAkSEQoJ",
            "b25seV9vcGVuGAIgASgIEhEKCW9ubHlfbG9uZxgDIAEoCCJJCg5UcmFkZXNS",
            "ZXNwb25zZRI3CgZ0cmFkZXMYASADKAsyJy5lYXN5dHJhZGUuZGJhZGFwdGVy",
            "LnRyYWRlLlRyYWRlTWVzc2FnZTL7BAoMVHJhZGVTZXJ2aWNlEmcKC0NyZWF0",
            "ZVRyYWRlEi0uZWFzeXRyYWRlLmRiYWRhcHRlci50cmFkZS5DcmVhdGVUcmFk",
            "ZVJlcXVlc3QaJy5lYXN5dHJhZGUuZGJhZGFwdGVyLnRyYWRlLlRyYWRlTWVz",
            "c2FnZSIAEmcKC1VwZGF0ZVRyYWRlEi0uZWFzeXRyYWRlLmRiYWRhcHRlci50",
            "cmFkZS5VcGRhdGVUcmFkZVJlcXVlc3QaJy5lYXN5dHJhZGUuZGJhZGFwdGVy",
            "LnRyYWRlLlRyYWRlTWVzc2FnZSIAElQKDUdldE9wZW5UcmFkZXMSFi5nb29n",
            "bGUucHJvdG9idWYuRW1wdHkaKS5lYXN5dHJhZGUuZGJhZGFwdGVyLnRyYWRl",
            "LlRyYWRlc1Jlc3BvbnNlIgASVwoQR2V0RXhwaXJlZFRyYWRlcxIWLmdvb2ds",
            "ZS5wcm90b2J1Zi5FbXB0eRopLmVhc3l0cmFkZS5kYmFkYXB0ZXIudHJhZGUu",
            "VHJhZGVzUmVzcG9uc2UiABJzChBHZXRBY2NvdW50VHJhZGVzEjIuZWFzeXRy",
            "YWRlLmRiYWRhcHRlci50cmFkZS5HZXRBY2NvdW50VHJhZGVzUmVxdWVzdBop",
            "LmVhc3l0cmFkZS5kYmFkYXB0ZXIudHJhZGUuVHJhZGVzUmVzcG9uc2UiABJ1",
            "ChVEZWxldGVUcmFkZXNPbGRlclRoYW4SLy5lYXN5dHJhZGUuZGJhZGFwdGVy",
            "LmNvbW1vbi5EZWxldGVCZWZvcmVSZXF1ZXN0GikuZWFzeXRyYWRlLmRiYWRh",
            "cHRlci5jb21tb24uQmF0Y2hSZXNwb25zZSIAQoEBCixjb20uZHluYXRyYWNl",
            "LmVhc3l0cmFkZS5kYmFkYXB0ZXIudHJhZGUuZ3JwY1ABWi5naXRodWIuY29t",
            "L2R5bmF0cmFjZS9lYXN5dHJhZGUvZGJhZGFwdGVyL3Byb3RvqgIeRWFzeVRy",
            "YWRlLkRiQWRhcHRlci5UcmFkZS5HcnBjYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::EasyTrade.DbAdapter.Common.Grpc.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EasyTrade.DbAdapter.Trade.Grpc.TradeMessage), global::EasyTrade.DbAdapter.Trade.Grpc.TradeMessage.Parser, new[]{ "Id", "AccountId", "InstrumentId", "Direction", "Quantity", "EntryPrice", "TimestampOpen", "TimestampClose", "TradeClosed", "TransactionHappened", "Status" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EasyTrade.DbAdapter.Trade.Grpc.CreateTradeRequest), global::EasyTrade.DbAdapter.Trade.Grpc.CreateTradeRequest.Parser, new[]{ "AccountId", "InstrumentId", "Direction", "Quantity", "EntryPrice", "TimestampOpen", "TimestampClose", "TradeClosed", "TransactionHappened", "Status" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EasyTrade.DbAdapter.Trade.Grpc.UpdateTradeRequest), global::EasyTrade.DbAdapter.Trade.Grpc.UpdateTradeRequest.Parser, new[]{ "Id", "TimestampClose", "TradeClosed", "Status" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EasyTrade.DbAdapter.Trade.Grpc.GetAccountTradesRequest), global::EasyTrade.DbAdapter.Trade.Grpc.GetAccountTradesRequest.Parser, new[]{ "AccountId", "OnlyOpen", "OnlyLong" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EasyTrade.DbAdapter.Trade.Grpc.TradesResponse), global::EasyTrade.DbAdapter.Trade.Grpc.TradesResponse.Parser, new[]{ "Trades" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TradeMessage : pb::IMessage<TradeMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TradeMessage> _parser = new pb::MessageParser<TradeMessage>(() => new TradeMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TradeMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EasyTrade.DbAdapter.Trade.Grpc.TradeServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TradeMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TradeMessage(TradeMessage other) : this() {
      id_ = other.id_;
      accountId_ = other.accountId_;
      instrumentId_ = other.instrumentId_;
      direction_ = other.direction_;
      quantity_ = other.quantity_;
      entryPrice_ = other.entryPrice_;
      timestampOpen_ = other.timestampOpen_ != null ? other.timestampOpen_.Clone() : null;
      timestampClose_ = other.timestampClose_ != null ? other.timestampClose_.Clone() : null;
      tradeClosed_ = other.tradeClosed_;
      transactionHappened_ = other.transactionHappened_;
      status_ = other.status_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TradeMessage Clone() {
      return new TradeMessage(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "account_id" field.</summary>
    public const int AccountIdFieldNumber = 2;
    private string accountId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AccountId {
      get { return accountId_; }
      set {
        accountId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "instrument_id" field.</summary>
    public const int InstrumentIdFieldNumber = 3;
    private string instrumentId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string InstrumentId {
      get { return instrumentId_; }
      set {
        instrumentId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "direction" field.</summary>
    public const int DirectionFieldNumber = 4;
    private string direction_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Direction {
      get { return direction_; }
      set {
        direction_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "quantity" field.</summary>
    public const int QuantityFieldNumber = 5;
    private double quantity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Quantity {
      get { return quantity_; }
      set {
        quantity_ = value;
      }
    }

    /// <summary>Field number for the "entry_price" field.</summary>
    public const int EntryPriceFieldNumber = 6;
    private double entryPrice_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double EntryPrice {
      get { return entryPrice_; }
      set {
        entryPrice_ = value;
      }
    }

    /// <summary>Field number for the "timestamp_open" field.</summary>
    public const int TimestampOpenFieldNumber = 7;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timestampOpen_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp TimestampOpen {
      get { return timestampOpen_; }
      set {
        timestampOpen_ = value;
      }
    }

    /// <summary>Field number for the "timestamp_close" field.</summary>
    public const int TimestampCloseFieldNumber = 8;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timestampClose_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp TimestampClose {
      get { return timestampClose_; }
      set {
        timestampClose_ = value;
      }
    }

    /// <summary>Field number for the "trade_closed" field.</summary>
    public const int TradeClosedFieldNumber = 9;
    private bool tradeClosed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool TradeClosed {
      get { return tradeClosed_; }
      set {
        tradeClosed_ = value;
      }
    }

    /// <summary>Field number for the "transaction_happened" field.</summary>
    public const int TransactionHappenedFieldNumber = 10;
    private bool transactionHappened_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool TransactionHappened {
      get { return transactionHappened_; }
      set {
        transactionHappened_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 11;
    private string status_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Status {
      get { return status_; }
      set {
        status_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TradeMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TradeMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (AccountId != other.AccountId) return false;
      if (InstrumentId != other.InstrumentId) return false;
      if (Direction != other.Direction) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Quantity, other.Quantity)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(EntryPrice, other.EntryPrice)) return false;
      if (!object.Equals(TimestampOpen, other.TimestampOpen)) return false;
      if (!object.Equals(TimestampClose, other.TimestampClose)) return false;
      if (TradeClosed != other.TradeClosed) return false;
      if (TransactionHappened != other.TransactionHappened) return false;
      if (Status != other.Status) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (AccountId.Length != 0) hash ^= AccountId.GetHashCode();
      if (InstrumentId.Length != 0) hash ^= InstrumentId.GetHashCode();
      if (Direction.Length != 0) hash ^= Direction.GetHashCode();
      if (Quantity != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Quantity);
      if (EntryPrice != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(EntryPrice);
      if (timestampOpen_ != null) hash ^= TimestampOpen.GetHashCode();
      if (timestampClose_ != null) hash ^= TimestampClose.GetHashCode();
      if (TradeClosed != false) hash ^= TradeClosed.GetHashCode();
      if (TransactionHappened != false) hash ^= TransactionHappened.GetHashCode();
      if (Status.Length != 0) hash ^= Status.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (AccountId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AccountId);
      }
      if (InstrumentId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(InstrumentId);
      }
      if (Direction.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Direction);
      }
      if (Quantity != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(Quantity);
      }
      if (EntryPrice != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(EntryPrice);
      }
      if (timestampOpen_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(TimestampOpen);
      }
      if (timestampClose_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(TimestampClose);
      }
      if (TradeClosed != false) {
        output.WriteRawTag(72);
        output.WriteBool(TradeClosed);
      }
      if (TransactionHappened != false) {
        output.WriteRawTag(80);
        output.WriteBool(TransactionHappened);
      }
      if (Status.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (AccountId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AccountId);
      }
      if (InstrumentId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(InstrumentId);
      }
      if (Direction.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Direction);
      }
      if (Quantity != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(Quantity);
      }
      if (EntryPrice != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(EntryPrice);
      }
      if (timestampOpen_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(TimestampOpen);
      }
      if (timestampClose_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(TimestampClose);
      }
      if (TradeClosed != false) {
        output.WriteRawTag(72);
        output.WriteBool(TradeClosed);
      }
      if (TransactionHappened != false) {
        output.WriteRawTag(80);
        output.WriteBool(TransactionHappened);
      }
      if (Status.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (AccountId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AccountId);
      }
      if (InstrumentId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(InstrumentId);
      }
      if (Direction.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Direction);
      }
      if (Quantity != 0D) {
        size += 1 + 8;
      }
      if (EntryPrice != 0D) {
        size += 1 + 8;
      }
      if (timestampOpen_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TimestampOpen);
      }
      if (timestampClose_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TimestampClose);
      }
      if (TradeClosed != false) {
        size += 1 + 1;
      }
      if (TransactionHappened != false) {
        size += 1 + 1;
      }
      if (Status.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Status);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TradeMessage other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.AccountId.Length != 0) {
        AccountId = other.AccountId;
      }
      if (other.InstrumentId.Length != 0) {
        InstrumentId = other.InstrumentId;
      }
      if (other.Direction.Length != 0) {
        Direction = other.Direction;
      }
      if (other.Quantity != 0D) {
        Quantity = other.Quantity;
      }
      if (other.EntryPrice != 0D) {
        EntryPrice = other.EntryPrice;
      }
      if (other.timestampOpen_ != null) {
        if (timestampOpen_ == null) {
          TimestampOpen = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        TimestampOpen.MergeFrom(other.TimestampOpen);
      }
      if (other.timestampClose_ != null) {
        if (timestampClose_ == null) {
          TimestampClose = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        TimestampClose.MergeFrom(other.TimestampClose);
      }
      if (other.TradeClosed != false) {
        TradeClosed = other.TradeClosed;
      }
      if (other.TransactionHappened != false) {
        TransactionHappened = other.TransactionHappened;
      }
      if (other.Status.Length != 0) {
        Status = other.Status;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            AccountId = input.ReadString();
            break;
          }
          case 26: {
            InstrumentId = input.ReadString();
            break;
          }
          case 34: {
            Direction = input.ReadString();
            break;
          }
          case 41: {
            Quantity = input.ReadDouble();
            break;
          }
          case 49: {
            EntryPrice = input.ReadDouble();
            break;
          }
          case 58: {
            if (timestampOpen_ == null) {
              TimestampOpen = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(TimestampOpen);
            break;
          }
          case 66: {
            if (timestampClose_ == null) {
              TimestampClose = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(TimestampClose);
            break;
          }
          case 72: {
            TradeClosed = input.ReadBool();
            break;
          }
          case 80: {
            TransactionHappened = input.ReadBool();
            break;
          }
          case 90: {
            Status = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            AccountId = input.ReadString();
            break;
          }
          case 26: {
            InstrumentId = input.ReadString();
            break;
          }
          case 34: {
            Direction = input.ReadString();
            break;
          }
          case 41: {
            Quantity = input.ReadDouble();
            break;
          }
          case 49: {
            EntryPrice = input.ReadDouble();
            break;
          }
          case 58: {
            if (timestampOpen_ == null) {
              TimestampOpen = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(TimestampOpen);
            break;
          }
          case 66: {
            if (timestampClose_ == null) {
              TimestampClose = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(TimestampClose);
            break;
          }
          case 72: {
            TradeClosed = input.ReadBool();
            break;
          }
          case 80: {
            TransactionHappened = input.ReadBool();
            break;
          }
          case 90: {
            Status = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CreateTradeRequest : pb::IMessage<CreateTradeRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CreateTradeRequest> _parser = new pb::MessageParser<CreateTradeRequest>(() => new CreateTradeRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CreateTradeRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EasyTrade.DbAdapter.Trade.Grpc.TradeServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateTradeRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateTradeRequest(CreateTradeRequest other) : this() {
      accountId_ = other.accountId_;
      instrumentId_ = other.instrumentId_;
      direction_ = other.direction_;
      quantity_ = other.quantity_;
      entryPrice_ = other.entryPrice_;
      timestampOpen_ = other.timestampOpen_ != null ? other.timestampOpen_.Clone() : null;
      timestampClose_ = other.timestampClose_ != null ? other.timestampClose_.Clone() : null;
      tradeClosed_ = other.tradeClosed_;
      transactionHappened_ = other.transactionHappened_;
      status_ = other.status_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateTradeRequest Clone() {
      return new CreateTradeRequest(this);
    }

    /// <summary>Field number for the "account_id" field.</summary>
    public const int AccountIdFieldNumber = 1;
    private string accountId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AccountId {
      get { return accountId_; }
      set {
        accountId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "instrument_id" field.</summary>
    public const int InstrumentIdFieldNumber = 2;
    private string instrumentId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string InstrumentId {
      get { return instrumentId_; }
      set {
        instrumentId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "direction" field.</summary>
    public const int DirectionFieldNumber = 3;
    private string direction_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Direction {
      get { return direction_; }
      set {
        direction_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "quantity" field.</summary>
    public const int QuantityFieldNumber = 4;
    private double quantity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Quantity {
      get { return quantity_; }
      set {
        quantity_ = value;
      }
    }

    /// <summary>Field number for the "entry_price" field.</summary>
    public const int EntryPriceFieldNumber = 5;
    private double entryPrice_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double EntryPrice {
      get { return entryPrice_; }
      set {
        entryPrice_ = value;
      }
    }

    /// <summary>Field number for the "timestamp_open" field.</summary>
    public const int TimestampOpenFieldNumber = 6;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timestampOpen_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp TimestampOpen {
      get { return timestampOpen_; }
      set {
        timestampOpen_ = value;
      }
    }

    /// <summary>Field number for the "timestamp_close" field.</summary>
    public const int TimestampCloseFieldNumber = 7;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timestampClose_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp TimestampClose {
      get { return timestampClose_; }
      set {
        timestampClose_ = value;
      }
    }

    /// <summary>Field number for the "trade_closed" field.</summary>
    public const int TradeClosedFieldNumber = 8;
    private bool tradeClosed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool TradeClosed {
      get { return tradeClosed_; }
      set {
        tradeClosed_ = value;
      }
    }

    /// <summary>Field number for the "transaction_happened" field.</summary>
    public const int TransactionHappenedFieldNumber = 9;
    private bool transactionHappened_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool TransactionHappened {
      get { return transactionHappened_; }
      set {
        transactionHappened_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 10;
    private string status_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Status {
      get { return status_; }
      set {
        status_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CreateTradeRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CreateTradeRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AccountId != other.AccountId) return false;
      if (InstrumentId != other.InstrumentId) return false;
      if (Direction != other.Direction) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Quantity, other.Quantity)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(EntryPrice, other.EntryPrice)) return false;
      if (!object.Equals(TimestampOpen, other.TimestampOpen)) return false;
      if (!object.Equals(TimestampClose, other.TimestampClose)) return false;
      if (TradeClosed != other.TradeClosed) return false;
      if (TransactionHappened != other.TransactionHappened) return false;
      if (Status != other.Status) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AccountId.Length != 0) hash ^= AccountId.GetHashCode();
      if (InstrumentId.Length != 0) hash ^= InstrumentId.GetHashCode();
      if (Direction.Length != 0) hash ^= Direction.GetHashCode();
      if (Quantity != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Quantity);
      if (EntryPrice != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(EntryPrice);
      if (timestampOpen_ != null) hash ^= TimestampOpen.GetHashCode();
      if (timestampClose_ != null) hash ^= TimestampClose.GetHashCode();
      if (TradeClosed != false) hash ^= TradeClosed.GetHashCode();
      if (TransactionHappened != false) hash ^= TransactionHappened.GetHashCode();
      if (Status.Length != 0) hash ^= Status.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AccountId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AccountId);
      }
      if (InstrumentId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(InstrumentId);
      }
      if (Direction.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Direction);
      }
      if (Quantity != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Quantity);
      }
      if (EntryPrice != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(EntryPrice);
      }
      if (timestampOpen_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(TimestampOpen);
      }
      if (timestampClose_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(TimestampClose);
      }
      if (TradeClosed != false) {
        output.WriteRawTag(64);
        output.WriteBool(TradeClosed);
      }
      if (TransactionHappened != false) {
        output.WriteRawTag(72);
        output.WriteBool(TransactionHappened);
      }
      if (Status.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AccountId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AccountId);
      }
      if (InstrumentId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(InstrumentId);
      }
      if (Direction.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Direction);
      }
      if (Quantity != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Quantity);
      }
      if (EntryPrice != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(EntryPrice);
      }
      if (timestampOpen_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(TimestampOpen);
      }
      if (timestampClose_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(TimestampClose);
      }
      if (TradeClosed != false) {
        output.WriteRawTag(64);
        output.WriteBool(TradeClosed);
      }
      if (TransactionHappened != false) {
        output.WriteRawTag(72);
        output.WriteBool(TransactionHappened);
      }
      if (Status.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AccountId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AccountId);
      }
      if (InstrumentId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(InstrumentId);
      }
      if (Direction.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Direction);
      }
      if (Quantity != 0D) {
        size += 1 + 8;
      }
      if (EntryPrice != 0D) {
        size += 1 + 8;
      }
      if (timestampOpen_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TimestampOpen);
      }
      if (timestampClose_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TimestampClose);
      }
      if (TradeClosed != false) {
        size += 1 + 1;
      }
      if (TransactionHappened != false) {
        size += 1 + 1;
      }
      if (Status.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Status);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CreateTradeRequest other) {
      if (other == null) {
        return;
      }
      if (other.AccountId.Length != 0) {
        AccountId = other.AccountId;
      }
      if (other.InstrumentId.Length != 0) {
        InstrumentId = other.InstrumentId;
      }
      if (other.Direction.Length != 0) {
        Direction = other.Direction;
      }
      if (other.Quantity != 0D) {
        Quantity = other.Quantity;
      }
      if (other.EntryPrice != 0D) {
        EntryPrice = other.EntryPrice;
      }
      if (other.timestampOpen_ != null) {
        if (timestampOpen_ == null) {
          TimestampOpen = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        TimestampOpen.MergeFrom(other.TimestampOpen);
      }
      if (other.timestampClose_ != null) {
        if (timestampClose_ == null) {
          TimestampClose = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        TimestampClose.MergeFrom(other.TimestampClose);
      }
      if (other.TradeClosed != false) {
        TradeClosed = other.TradeClosed;
      }
      if (other.TransactionHappened != false) {
        TransactionHappened = other.TransactionHappened;
      }
      if (other.Status.Length != 0) {
        Status = other.Status;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            AccountId = input.ReadString();
            break;
          }
          case 18: {
            InstrumentId = input.ReadString();
            break;
          }
          case 26: {
            Direction = input.ReadString();
            break;
          }
          case 33: {
            Quantity = input.ReadDouble();
            break;
          }
          case 41: {
            EntryPrice = input.ReadDouble();
            break;
          }
          case 50: {
            if (timestampOpen_ == null) {
              TimestampOpen = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(TimestampOpen);
            break;
          }
          case 58: {
            if (timestampClose_ == null) {
              TimestampClose = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(TimestampClose);
            break;
          }
          case 64: {
            TradeClosed = input.ReadBool();
            break;
          }
          case 72: {
            TransactionHappened = input.ReadBool();
            break;
          }
          case 82: {
            Status = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            AccountId = input.ReadString();
            break;
          }
          case 18: {
            InstrumentId = input.ReadString();
            break;
          }
          case 26: {
            Direction = input.ReadString();
            break;
          }
          case 33: {
            Quantity = input.ReadDouble();
            break;
          }
          case 41: {
            EntryPrice = input.ReadDouble();
            break;
          }
          case 50: {
            if (timestampOpen_ == null) {
              TimestampOpen = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(TimestampOpen);
            break;
          }
          case 58: {
            if (timestampClose_ == null) {
              TimestampClose = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(TimestampClose);
            break;
          }
          case 64: {
            TradeClosed = input.ReadBool();
            break;
          }
          case 72: {
            TransactionHappened = input.ReadBool();
            break;
          }
          case 82: {
            Status = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UpdateTradeRequest : pb::IMessage<UpdateTradeRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpdateTradeRequest> _parser = new pb::MessageParser<UpdateTradeRequest>(() => new UpdateTradeRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UpdateTradeRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EasyTrade.DbAdapter.Trade.Grpc.TradeServiceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateTradeRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateTradeRequest(UpdateTradeRequest other) : this() {
      id_ = other.id_;
      timestampClose_ = other.timestampClose_ != null ? other.timestampClose_.Clone() : null;
      tradeClosed_ = other.tradeClosed_;
      status_ = other.status_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateTradeRequest Clone() {
      return new UpdateTradeRequest(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "timestamp_close" field.</summary>
    public const int TimestampCloseFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timestampClose_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp TimestampClose {
      get { return timestampClose_; }
      set {
        timestampClose_ = value;
      }
    }

    /// <summary>Field number for the "trade_closed" field.</summary>
    public const int TradeClosedFieldNumber = 3;
    private bool tradeClosed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool TradeClosed {
      get { return tradeClosed_; }
      set {
        tradeClosed_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 4;
    private string status_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Status {
      get { return status_; }
      set {
        status_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UpdateTradeRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UpdateTradeRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(TimestampClose, other.TimestampClose)) return false;
      if (TradeClosed != other.TradeClosed) return false;
      if (Status != other.Status) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (timestampClose_ != null) hash ^= TimestampClose.GetHashCode();
      if (TradeClosed != false) hash ^= TradeClosed.GetHashCode();
      if (Status.Length != 0) hash ^= Status.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (timestampClose_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TimestampClose);
      }
      if (TradeClosed != false) {
        output.WriteRawTag(24);
        output.WriteBool(TradeClosed);
      }
      if (Status.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (timestampClose_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TimestampClose);
      }
      if (TradeClosed != false) {
        output.WriteRawTag(24);
        output.WriteBool(TradeClosed);
      }
      if (Status.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (timestampClose_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TimestampClose);
      }
      if (TradeClosed != false) {
        size += 1 + 1;
      }
      if (Status.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Status);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UpdateTradeRequest other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.timestampClose_ != null) {
        if (timestampClose_ == null) {
          TimestampClose = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        TimestampClose.MergeFrom(other.TimestampClose);
      }
      if (other.TradeClosed != false) {
        TradeClosed = other.TradeClosed;
      }
      if (other.Status.Length != 0) {
        Status = other.Status;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            if (timestampClose_ == null) {
              TimestampClose = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(TimestampClose);
            break;
          }
          case 24: {
            TradeClosed = input.ReadBool();
            break;
          }
          case 34: {
            Status = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            if (timestampClose_ == null) {
              TimestampClose = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(TimestampClose);
            break;
          }
          case 24: {
            TradeClosed = input.ReadBool();
            break;
          }
          case 34: {
            Status = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetAccountTradesRequest : pb::IMessage<GetAccountTradesRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetAccountTradesRequest> _parser = new pb::MessageParser<GetAccountTradesRequest>(() => new GetAccountTradesRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetAccountTradesRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EasyTrade.DbAdapter.Trade.Grpc.TradeServiceReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetAccountTradesRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetAccountTradesRequest(GetAccountTradesRequest other) : this() {
      accountId_ = other.accountId_;
      onlyOpen_ = other.onlyOpen_;
      onlyLong_ = other.onlyLong_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetAccountTradesRequest Clone() {
      return new GetAccountTradesRequest(this);
    }

    /// <summary>Field number for the "account_id" field.</summary>
    public const int AccountIdFieldNumber = 1;
    private string accountId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AccountId {
      get { return accountId_; }
      set {
        accountId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "only_open" field.</summary>
    public const int OnlyOpenFieldNumber = 2;
    private bool onlyOpen_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool OnlyOpen {
      get { return onlyOpen_; }
      set {
        onlyOpen_ = value;
      }
    }

    /// <summary>Field number for the "only_long" field.</summary>
    public const int OnlyLongFieldNumber = 3;
    private bool onlyLong_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool OnlyLong {
      get { return onlyLong_; }
      set {
        onlyLong_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetAccountTradesRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetAccountTradesRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AccountId != other.AccountId) return false;
      if (OnlyOpen != other.OnlyOpen) return false;
      if (OnlyLong != other.OnlyLong) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AccountId.Length != 0) hash ^= AccountId.GetHashCode();
      if (OnlyOpen != false) hash ^= OnlyOpen.GetHashCode();
      if (OnlyLong != false) hash ^= OnlyLong.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AccountId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AccountId);
      }
      if (OnlyOpen != false) {
        output.WriteRawTag(16);
        output.WriteBool(OnlyOpen);
      }
      if (OnlyLong != false) {
        output.WriteRawTag(24);
        output.WriteBool(OnlyLong);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AccountId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AccountId);
      }
      if (OnlyOpen != false) {
        output.WriteRawTag(16);
        output.WriteBool(OnlyOpen);
      }
      if (OnlyLong != false) {
        output.WriteRawTag(24);
        output.WriteBool(OnlyLong);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AccountId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AccountId);
      }
      if (OnlyOpen != false) {
        size += 1 + 1;
      }
      if (OnlyLong != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetAccountTradesRequest other) {
      if (other == null) {
        return;
      }
      if (other.AccountId.Length != 0) {
        AccountId = other.AccountId;
      }
      if (other.OnlyOpen != false) {
        OnlyOpen = other.OnlyOpen;
      }
      if (other.OnlyLong != false) {
        OnlyLong = other.OnlyLong;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            AccountId = input.ReadString();
            break;
          }
          case 16: {
            OnlyOpen = input.ReadBool();
            break;
          }
          case 24: {
            OnlyLong = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            AccountId = input.ReadString();
            break;
          }
          case 16: {
            OnlyOpen = input.ReadBool();
            break;
          }
          case 24: {
            OnlyLong = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TradesResponse : pb::IMessage<TradesResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TradesResponse> _parser = new pb::MessageParser<TradesResponse>(() => new TradesResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TradesResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EasyTrade.DbAdapter.Trade.Grpc.TradeServiceReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TradesResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TradesResponse(TradesResponse other) : this() {
      trades_ = other.trades_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TradesResponse Clone() {
      return new TradesResponse(this);
    }

    /// <summary>Field number for the "trades" field.</summary>
    public const int TradesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::EasyTrade.DbAdapter.Trade.Grpc.TradeMessage> _repeated_trades_codec
        = pb::FieldCodec.ForMessage(10, global::EasyTrade.DbAdapter.Trade.Grpc.TradeMessage.Parser);
    private readonly pbc::RepeatedField<global::EasyTrade.DbAdapter.Trade.Grpc.TradeMessage> trades_ = new pbc::RepeatedField<global::EasyTrade.DbAdapter.Trade.Grpc.TradeMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EasyTrade.DbAdapter.Trade.Grpc.TradeMessage> Trades {
      get { return trades_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TradesResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TradesResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!trades_.Equals(other.trades_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= trades_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      trades_.WriteTo(output, _repeated_trades_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      trades_.WriteTo(ref output, _repeated_trades_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += trades_.CalculateSize(_repeated_trades_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TradesResponse other) {
      if (other == null) {
        return;
      }
      trades_.Add(other.trades_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            trades_.AddEntriesFrom(input, _repeated_trades_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            trades_.AddEntriesFrom(ref input, _repeated_trades_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
