global:
  dynatrace:
    version: 1.1.1
  image:
    # Base repository for all images. Individual services can override the repository if needed.
    baseRepository: "europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade"
    tag: latest
  database:
    # Plaintext default. Ignored when existingSecret.name is set.
    password: "yourStrong(!)Password"
    # Set name to source the password from an existing Kubernetes Secret instead.
    existingSecret:
      name: ""
      key: "password"
    name: TradeManagement
    # supports: ["mssql", "postgres"]
    type: mssql

  # Global labels to be added to all resources
  labels: {}
  # Environment variables to be added to all pods
  env: {}

background-service:
  enabled: true
  livenessProbe:
    httpGet:
      path: /livez
      port: http
    initialDelaySeconds: 15
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 5
    periodSeconds: 5
  rbac:
    create: true
    rules:
      - apiGroups: [""]
        resources: ["services", "pods", "events"]
        verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
      - apiGroups: ["apps"]
        resources: ["deployments", "replicasets"]
        verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
  env:
    OFFER_SERVICE_ADDRESS: "http://{{ .Release.Name }}-offerservice:8080"
    CREDIT_CARD_ORDER_SERVICE_ADDRESS: "http://{{ .Release.Name }}-credit-card-order-service:8080"
    THIRD_PARTY_DELAY: "500"
    THIRD_PARTY_RATE: "900"
    FEATURE_FLAG_SERVICE_ADDRESS: "http://{{ .Release.Name }}-feature-flag-service:8080"
    POD_NAMESPACE: "{{ .Release.Namespace }}"
    HIGH_CPU_USAGE_BROKER_SERVICE_CPU_LIMIT: "300m"
    HIGH_CPU_USAGE_BROKER_SERVICE_NAME: "{{ .Release.Name }}-broker-service"
    DB_ADAPTER_SERVICE_ADDRESS: "{{ .Release.Name }}-db-adapter:50051"
    DELAY_CHANCE_PERCENT: "20"
  resources:
    requests:
      cpu: 30m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
  service:
    enabled: true
    port: 8080

broker-service:
  enabled: true
  env:
    USER_SERVICE_HOSTANDPORT: "{{ .Release.Name }}-user-service:8080"
    PRICINGSERVICE_HOSTANDPORT: "{{ .Release.Name }}-pricing-service:8080"
    FEATURE_FLAG_SERVICE_PROTOCOL: http
    FEATURE_FLAG_SERVICE_BASE_URL: "{{ .Release.Name }}-feature-flag-service"
    FEATURE_FLAG_SERVICE_PORT: "8080"
    PROXY_PREFIX: "broker-service"
    DB_ADAPTER_ADDRESS: "{{ .Release.Name }}-db-adapter:50051"
  livenessProbe:
    httpGet:
      path: /livez
      port: http
    initialDelaySeconds: 15
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 5
    periodSeconds: 5
  resources:
    requests:
      cpu: 150m
      memory: 350Mi
    limits:
      cpu: 600m
      memory: 350Mi
  service:
    enabled: true
    port: 8080

credit-card-order-service:
  enabled: true
  env:
    PROXY_PREFIX: "credit-card-order-service"
    THIRD_PARTY_SERVICE_HOSTANDPORT: "{{ .Release.Name }}-background-service:8080"
    WORK_DELAY: "300"
    WORK_RATE: "900"
    JAVA_TOOL_OPTIONS: "-XX:-OmitStackTraceInFastThrow"
    FEATURE_FLAG_SERVICE_PROTOCOL: http
    FEATURE_FLAG_SERVICE_BASE_URL: "{{ .Release.Name }}-feature-flag-service"
    FEATURE_FLAG_SERVICE_PORT: "8080"
    DB_ADAPTER_ADDRESS: "{{ .Release.Name }}-db-adapter:50051"
  livenessProbe:
    httpGet:
      path: /livez
      port: http
    initialDelaySeconds: 15
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 5
    periodSeconds: 5
  resources:
    requests:
      cpu: 20m
      memory: 650Mi
    limits:
      cpu: 500m
      memory: 650Mi
  service:
    enabled: true
    port: 8080

db-mssql:
  enabled: true
  workloadType: statefulset
  envFromSecret:
    SA_PASSWORD:
      name: '{{ include "easytrade.dbPasswordSecretName" . }}'
      key: '{{ include "easytrade.dbPasswordSecretKey" . }}'
  livenessProbe:
    tcpSocket:
      port: http
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    tcpSocket:
      port: http
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 6
    successThreshold: 1
  resources:
    requests:
      cpu: 500m
      memory: 1.5Gi
    limits:
      cpu: "2"
      memory: 1.5Gi
  service:
    enabled: true
    port: 1433
  # Enabling persistence will create a PersistentVolumeClaim for the database data
  # persistence:
  #   enabled: true
  #   mountPath: /var/opt/mssql
  #   size: 10Gi

db-postgres:
  enabled: false
  workloadType: statefulset
  env:
    POSTGRES_DB: "{{ .Values.global.database.name }}"
  envFromSecret:
    POSTGRES_PASSWORD:
      name: '{{ include "easytrade.dbPasswordSecretName" . }}'
      key: '{{ include "easytrade.dbPasswordSecretKey" . }}'
  livenessProbe:
    tcpSocket:
      port: http
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    tcpSocket:
      port: http
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 6
    successThreshold: 1
  resources:
    requests:
      cpu: 500m
      memory: 1.5Gi
    limits:
      cpu: "2"
      memory: 1.5Gi
  service:
    enabled: true
    port: 5432
  # Enabling persistence will create a PersistentVolumeClaim for the database data
  # persistence:
  #   enabled: true
  #   mountPath: /var/lib/postgresql/data
  #   size: 10Gi

db-adapter:
  enabled: true
  env:
    DB_TYPE: "{{ .Values.global.database.type }}"
  envFromSecret:
    DB_URL:
      name: "{{ .Release.Name }}-connection-strings"
      key: "DB_URL"
  livenessProbe:
    httpGet:
      path: /livez
      port: 8080
    initialDelaySeconds: 15
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /readyz
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 5
  resources:
    requests:
      cpu: 10m
      memory: 30Mi
    limits:
      cpu: 100m
      memory: 30Mi
  service:
    enabled: true
    port: 50051

feature-flag-service:
  enabled: true
  env:
    FEATURE_FLAG_SERVICE_PROTOCOL: http
    FEATURE_FLAG_SERVICE_BASE_URL: "{{ .Release.Name }}-feature-flag-service"
    FEATURE_FLAG_SERVICE_PORT: "8080"
  livenessProbe:
    httpGet:
      path: /livez
      port: http
    initialDelaySeconds: 15
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 5
    periodSeconds: 5
  resources:
    requests:
      cpu: 30m
      memory: 600Mi
    limits:
      cpu: 200m
      memory: 600Mi
  service:
    enabled: true
    port: 8080

frontend:
  enabled: true
  livenessProbe:
    tcpSocket:
      port: http
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 5
    timeoutSeconds: 3
    periodSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  resources:
    requests:
      cpu: 10m
      memory: 75Mi
    limits:
      cpu: 100m
      memory: 75Mi
  service:
    enabled: true
    port: 3000

frontendreverseproxy:
  enabled: true
  env:
    FRONTEND_REVERSE_PROXY_PORT: "8080"
    BROKER_SERVICE_URL: "http://{{ .Release.Name }}-broker-service:8080"
    CREDIT_CARD_ORDER_SERVICE_URL: "http://{{ .Release.Name }}-credit-card-order-service:8080"
    FEATURE_FLAG_SERVICE_URL: "http://{{ .Release.Name }}-feature-flag-service:8080"
    FRONTEND_URL: "http://{{ .Release.Name }}-frontend:3000"
    OFFER_SERVICE_URL: "http://{{ .Release.Name }}-offerservice:8080"
    PRICING_SERVICE_URL: "http://{{ .Release.Name }}-pricing-service:8080"
    USER_SERVICE_URL: "http://{{ .Release.Name }}-user-service:8080"
    BACKGROUND_SERVICE_URL: "http://{{ .Release.Name }}-background-service:8080"
  livenessProbe:
    tcpSocket:
      port: http
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 5
    timeoutSeconds: 3
    periodSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 100Mi
  service:
    enabled: true
    ports:
      - port: 8080
        targetPort: 8080
        protocol: TCP
        name: http

loadgen:
  enabled: true
  env:
    EASYTRADE_URL: "http://{{ .Release.Name }}-frontendreverseproxy:8080"
    RARE_VISITS_INTERVAL_MINUTES: "60"
  livenessProbe:
    httpGet:
      path: /livez
      port: 8080
    initialDelaySeconds: 15
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /readyz
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 5
  resources:
    requests:
      cpu: "1"
      memory: 1Gi
    limits:
      cpu: "3"
      memory: 3Gi

offerservice:
  enabled: true
  env:
    DB_ADAPTER_ADDRESS: "{{ .Release.Name }}-db-adapter:50051"
    USER_SERVICE_PORT: "8080"
    USER_SERVICE_BASE_URL: "{{ .Release.Name }}-user-service"
    FEATURE_FLAG_SERVICE_PROTOCOL: http
    FEATURE_FLAG_SERVICE_BASE_URL: "{{ .Release.Name }}-feature-flag-service"
    FEATURE_FLAG_SERVICE_PORT: "8080"
  livenessProbe:
    httpGet:
      path: /livez
      port: http
    initialDelaySeconds: 15
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 5
    periodSeconds: 5
  resources:
    requests:
      cpu: 100m
      memory: 150Mi
    limits:
      cpu: "1"
      memory: 1Gi
  service:
    enabled: true
    port: 8080

pricing-service:
  enabled: true
  env:
    PROXY_PREFIX: "pricing-service"
    DB_ADAPTER_ADDRESS: "{{ .Release.Name }}-db-adapter:50051"
  livenessProbe:
    httpGet:
      path: /livez
      port: http
    initialDelaySeconds: 15
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 5
    periodSeconds: 5
  resources:
    requests:
      cpu: 20m
      memory: 80Mi
    limits:
      cpu: 200m
      memory: 80Mi
  service:
    enabled: true
    port: 8080

user-service:
  enabled: true
  env:
    PROXY_PREFIX: "user-service"
    DB_ADAPTER_ADDRESS: "{{ .Release.Name }}-db-adapter:50051"
  livenessProbe:
    httpGet:
      path: /livez
      port: http
    initialDelaySeconds: 15
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /readyz
      port: http
    initialDelaySeconds: 5
    periodSeconds: 5
  resources:
    requests:
      cpu: 20m
      memory: 450Mi
    limits:
      cpu: 200m
      memory: 450Mi
  service:
    enabled: true
    port: 8080
