FROM node:22.13.1-alpine3.21@sha256:e2b39f7b64281324929257d0f8004fb6cb4bf0fdfb9aa8cedb235a766aec31da

LABEL ENV="DEV"

WORKDIR /app

VOLUME ["./src"]

COPY ["*.json", "vite.config.ts", "index.html", "./"]

RUN npm install

CMD ["npm", "run", "dev", "--", "--host", "-d"]