FROM node:24.11.0-alpine3.22@sha256:f36fed0b2129a8492535e2853c64fbdbd2d29dc1219ee3217023ca48aebd3787

LABEL ENV="DEV"

WORKDIR /app

VOLUME ["./src"]

COPY ["*.json", "vite.config.ts", "index.html", "./"]

RUN npm install

CMD ["npm", "run", "dev", "--", "--host", "-d"]
