FROM node:22.17.1-alpine3.21@sha256:f00440c423ce5657e4d2347fa3b9bf5887389f6fcf3daa25cc79ea11a6a00f80

LABEL ENV="DEV"

WORKDIR /app

VOLUME ["./src"]

COPY ["*.json", "vite.config.ts", "index.html", "./"]

RUN npm install

CMD ["npm", "run", "dev", "--", "--host", "-d"]
