apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountservice
spec:
  selector:
    matchLabels:
      app: accountservice
  template:
    metadata:
      labels:
        app: accountservice
    spec:
      containers:
        - name: accountservice
          image: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/accountservice:4d5adb3
          ports:
            - containerPort: 8080
          env:
            - name: MANAGER_HOSTANDPORT
              value: "manager:8080"
            - name: PROXY_PREFIX
              value: "accountservice"
          resources:
            requests:
              cpu: 30m
              memory: 600Mi
            limits:
              memory: 600Mi
---
apiVersion: v1
kind: Service
metadata:
  name: accountservice
spec:
  type: ClusterIP
  selector:
    app: accountservice
  ports:
    - name: http
      port: 8080
      targetPort: 8080
