apiVersion: apps/v1
kind: Deployment
metadata:
  name: contentcreator
spec:
  selector:
    matchLabels:
      app: contentcreator
  template:
    metadata:
      labels:
        app: contentcreator
    spec:
      containers:
        - name: contentcreator
          image: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/contentcreator:fa6ccf2
          env:
            - name: MSSQL_CONNECTIONSTRING
              valueFrom:
                configMapKeyRef:
                  name: connection-strings
                  key: JAVA_CONNECTION_STRING
          resources:
            requests:
              cpu: 10m
              memory: 400Mi
            limits:
              memory: 400Mi
