apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-card-order-service
spec:
  selector:
    matchLabels:
      app: credit-card-order-service
  template:
    metadata:
      labels:
        app: credit-card-order-service
    spec:
      containers:
        - name: credit-card-order-service
          image: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/credit-card-order-service:4d5adb3
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: feature-flag-service-setup
          env:
            - name: PROXY_PREFIX
              value: "credit-card-order-service"
            - name: THIRD_PARTY_SERVICE_HOSTANDPORT
              value: "third-party-service:8080"
            - name: WORK_DELAY
              value: "300"
            - name: WORK_RATE
              value: "900"
            - name: MSSQL_CONNECTIONSTRING
              valueFrom:
                configMapKeyRef:
                  name: connection-strings
                  key: JAVA_CONNECTION_STRING
          resources:
            requests:
              cpu: 20m
              memory: 600Mi
            limits:
              memory: 600Mi
---
apiVersion: v1
kind: Service
metadata:
  name: credit-card-order-service
spec:
  type: ClusterIP
  selector:
    app: credit-card-order-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
