configs:
  - id: easytrade
    config:
      name: EasyTrade
      template: easytrade.json
      skip: false
    type:
      api: application-web
  - id: easytrade-proxy
    config:
      parameters:
        easytrade_web_app:
          type: reference
          configType: application-web
          configId: easytrade
          property: id
      template: easytrade-proxy.json
      skip: false
    type:
      settings:
        schema: builtin:rum.web.app-detection
        scope: environment
  - id: easytrade-domain
    config:
      template: easytrade-domain.json
      parameters:
        applicationId:
          type: reference
          configType: application-web
          configId: easytrade
          property: id
        domain:
          name: DOMAIN
          type: environment
      skip: false
    type:
      settings:
        schema: builtin:rum.web.app-detection
        scope: environment
