configs:
  - id: outbound-connections
    config:
      template: outbound-connections.json
      parameters:
        connectionList:
          type: list
          values:
            - slack.com
      skip: false
    type:
      settings:
        schema: builtin:dt-javascript-runtime.allowed-outbound-connections
        scope: environment
