configs:
  - id: easytrade-k8s-bizevents-frontend
    config:
      name: easytrade-k8s-bizevents-frontend
      template: easytrade-k8s-bizevents-frontend.json
      skip: false
      parameters:
        timeframeMinutes: 15
        referenceTimeframeMinutes: 15
        depositStartReferenceCount: 60
        depositFinishReferenceCount: 60
        depositErrorReferenceCount: 5
        withdrawStartReferenceCount: 15
        withdrawFinishReferenceCount: 15
        withdrawErrorReferenceCount: 5
        buyStartReferenceCount: 10
        buyFinishReferenceCount: 10
        buyErrorReferenceCount: 5
        sellStartReferenceCount: 10
        sellFinishReferenceCount: 10
        sellErrorReferenceCount: 5
    type:
      settings:
        schema: app:dynatrace.site.reliability.guardian:guardians
        scope: environment
  - id: easytrade-k8s-loadgen-visits
    config:
      name: easytrade-k8s-loadgen-visits
      template: easytrade-k8s-loadgen-visits.json
      skip: false
      parameters:
        timeframeMinutes: 15
        referenceTimeframeMinutes: 15
        visitsReferenceCount: 50
        failureRatePercentThreshold: 15
        loadgenContainerName: loadgen
        visitStartMsg: Running visit
        visitErrorMsg: Worker had error when running visit
    type:
      settings:
        schema: app:dynatrace.site.reliability.guardian:guardians
        scope: environment
  - id: easytrade-k8s-bizevents
    config:
      name: easytrade-k8s-bizevents
      template: easytrade-k8s-bizevents.json
      skip: false
      parameters:
        timeframeMinutes: 15
        referenceTimeframeMinutes: 15
        totalReferenceCount: 8500
        depositReferenceCount: 45
        withdrawReferenceCount: 10
        longBuySellReferenceCount: 70
        quickBuySellReferenceCount: 20
        balanceReferenceCount: 100
        instrumentsReferenceCount: 115
        flagReferenceCount: 1100
        offerReferenceCount: 1100
        managerPackageReferenceCount: 1100
        managerProductReferenceCount: 1100
        loginReferenceCount: 120
        logoutReferenceCount: 120
        priceReferenceCount: 150
        managerAccountReferenceCount: 120
        latestPriceReferenceCount: 150
        longProcessReferenceCount: 10
        accountReferenceCount: 120
    type:
      settings:
        schema: app:dynatrace.site.reliability.guardian:guardians
        scope: environment
