name: Build easytrade on branch
on:
  push:
    branches:
      - "**"
      - "!main"
    paths:
      - .github/**
      - kubernetes-manifests/**
      - skaffold.yaml
      - src/**

  workflow_call:
    secrets:
      SNYK_API_TOKEN:
        required: true

env:
  CONTAINER_REGISTRY: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade

jobs:
  snyk:
    uses: ./.github/workflows/snyk.yaml
    permissions:
      security-events: write
      contents: read
      actions: read
    secrets:
      SNYK_API_TOKEN: ${{ secrets.SNYK_API_TOKEN }}

  calc-version:
    uses: ./.github/workflows/calc-version.yaml
    with:
      release-branch: main

  build-easytrade:
    runs-on: ubuntu-24.04
    needs: calc-version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push images
        uses: ./.github/actions/build-push-images
        with:
          push: false
          tag: ${{ steps.calc-version.outputs.version }}
          registry: ${{ env.CONTAINER_REGISTRY }}
